project_id = "vtmrimrrppuclciolzuw"

[functions.incoming]
verify_jwt = false

[functions.notify-story-approval]
verify_jwt = false

[functions.send-scheduled-posts]
verify_jwt = false

[functions.publish-proxy]
verify_jwt = false

[functions.submit-to-n8n]
verify_jwt = true

[functions.reset-daily-quota]
verify_jwt = false

[functions.increment-quota]
verify_jwt = false