project_id = "vtmrimrrppuclciolzuw"

[functions.incoming]
verify_jwt = false

[functions.callback]
verify_jwt = false

[functions.send-scheduled-posts]
verify_jwt = false

[functions.publish-to-getlate]
verify_jwt = false