// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
type Admin = any;
export type NoticiaGemea = {
    id: string;
    titulo: string;
    estado: string;
    url: string | null;
    edicao_numero: number | null;
};
/**
 * Devolve um mapa `url normalizado → notícia já existente` para os URLs dados.
 * Consulta em lotes para não estourar o tamanho do pedido.
 */
export declare function procurarDuplicadosUrl(admin: Admin, urls: Array<string | null | undefined>): Promise<Map<string, NoticiaGemea>>;
/** Texto curto e legível para explicar de onde vem o duplicado. */
export declare function descreverGemea(g: NoticiaGemea): string;
export {};
