// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type MotivoLixo = "pagina_institucional" | "titulo_vazio" | "titulo_sem_conteudo";
/**
 * Devolve o motivo pelo qual o título deve ser descartado, ou `null` quando é
 * uma notícia legítima. Nunca chama IA — corre antes de qualquer extracção.
 */
export declare function motivoTituloLixo(titulo: string, descricao?: string | null, url?: string | null): MotivoLixo | null;
export declare function ehTituloLixo(titulo: string, descricao?: string | null, url?: string | null): boolean;
/** Rótulo legível para os resumos de cada corrida. */
export declare function descreverMotivoLixo(m: MotivoLixo): string;
