// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export interface OpcoesSeleccao {
    max: number;
    /** Tecto por fonte enquanto houver material de outras fontes. Default 2. */
    maxPorFonte?: number;
    /** Tecto por categoria enquanto houver material de outras categorias. Default 3. */
    maxPorCategoria?: number;
}
export interface ChavesSeleccao<T> {
    fonte: (item: T) => string;
    categoria?: (item: T) => string;
    /** Maior = mais recente/prioritário. */
    prioridade: (item: T) => number;
}
export interface ResultadoSeleccao<T> {
    seleccionados: T[];
    /** Quantos entraram por fonte (nome/id → contagem). */
    porFonte: Record<string, number>;
}
export declare function seleccionarDiverso<T>(itens: T[], chaves: ChavesSeleccao<T>, opts: OpcoesSeleccao): ResultadoSeleccao<T>;
/** Chave de título normalizada, para deduplicação dentro da mesma corrida. */
export declare function chaveTitulo(titulo: string): string;
/** Semelhança simples por palavras (Jaccard sobre palavras com 4+ letras). */
export declare function semelhancaTitulos(a: string, b: string): number;
