// @vitest-environment node
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {briefInicial,estruturaManual} from '../../supabase/functions/_shared/roteiros/modelo';
const db=new PGlite();const project='00000000-0000-4000-8000-000000000001';const user='00000000-0000-4000-8000-000000000009';
const brief=briefInicial();const fonte={tipo:'texto',titulo:'Fonte de teste',texto:'O texto da fonte é guardado de forma imutável e tem mais de quarenta caracteres.'};
const q=async(sql:string,args:unknown[]=[]) => (await db.query<Record<string,any>>(sql,args)).rows;
const create=async(id=crypto.randomUUID(),f=fonte)=> (await q('SELECT * FROM rv_criar($1,$2,$3::jsonb,$4::jsonb)',[id,project,JSON.stringify(f),JSON.stringify(brief)]))[0];
beforeAll(async()=>{await db.exec(readFileSync('scripts/roteiros/base-local.sql','utf8'));await db.exec(readFileSync('drizzle/migrations/0045_roteiros_reels.sql','utf8'));await db.exec(readFileSync('drizzle/migrations/0046_roteiros_refinamento.sql','utf8'));await db.exec(`SET request.jwt.claim.sub='${user}'`);},30000);
afterAll(()=>db.close());
describe('roteiros: migração executada em PostgreSQL',()=>{
 it('cria uma vez, guarda e recusa gravação obsoleta; conserva versões e fonte',async()=>{const id=crypto.randomUUID();const a=await create(id);expect((await create(id)).id).toBe(id);const v=estruturaManual('hva','Meu roteiro');v.cenas[0].locucao='O meu texto editado.';const doc={variantes:[v],selecionada:v.id};const b=(await q('SELECT * FROM rv_guardar($1,1,$2::jsonb,$3::jsonb)',[id,JSON.stringify(brief),JSON.stringify(doc)]))[0];expect(b.revisao).toBe(2);expect(b.fonte).toEqual(a.fonte);await expect(q('SELECT rv_guardar($1,1,$2::jsonb,$3::jsonb)',[id,JSON.stringify(brief),JSON.stringify(doc)])).rejects.toMatchObject({code:'MC409'});expect(await q('SELECT revisao FROM rv_versoes WHERE roteiro_id=$1 ORDER BY revisao',[id])).toEqual([{revisao:1},{revisao:2}]);});
 it('relê a notícia no servidor, rejeita hash antigo e notícia não aprovada',async()=>{const n=(await q("INSERT INTO rv_noticias_local(titulo,texto) VALUES('Notícia','O conteúdo é real para este teste e é relido no servidor.') RETURNING id"))[0];const s=(await q('SELECT nl_curadoria_snapshot($1) AS s',[n.id]))[0].s;const r=await create(crypto.randomUUID(),{...s,tipo:'curadoria',texto:'Texto adulterado'});expect(r.fonte.texto).toBe(s.texto);await expect(create(crypto.randomUUID(),{...s,tipo:'curadoria',hash:'velho'})).rejects.toMatchObject({code:'MC409'});await q("UPDATE rv_noticias_local SET estado='rejeitada' WHERE id=$1",[n.id]);await expect(create(crypto.randomUUID(),{...s,tipo:'curadoria'})).rejects.toMatchObject({code:'MC409'});});
 it('não deixa outro projeto ler ou escrever e bloqueia escritas diretas',async()=>{const a=await create();await db.exec('SET ROLE authenticated');await expect(q("UPDATE rv_roteiros SET fonte='{}' WHERE id=$1",[a.id])).rejects.toMatchObject({code:'42501'});await expect(q('DELETE FROM rv_versoes')).rejects.toMatchObject({code:'42501'});await db.exec("SET request.jwt.claim.sub='00000000-0000-4000-8000-000000000099'");expect(await q('SELECT id FROM rv_roteiros')).toEqual([]);await expect(create()).rejects.toMatchObject({code:'42501'});await expect(q("SELECT rv_guardar($1,1,$2::jsonb,'{\"variantes\":[],\"selecionada\":null}')",[a.id,JSON.stringify(brief)])).rejects.toMatchObject({code:'42501'});await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${user}'`);});
 it('recusa documentos e briefings inválidos no servidor',async()=>{const a=await create();await expect(q('SELECT rv_guardar($1,1,$2::jsonb,$3::jsonb)',[a.id,JSON.stringify({...brief,frameworks:[]}),JSON.stringify({variantes:[],selecionada:null})])).rejects.toMatchObject({code:'22023'});await expect(q('SELECT rv_guardar($1,1,$2::jsonb,$3::jsonb)',[a.id,JSON.stringify(brief),JSON.stringify({variantes:[],selecionada:'inexistente'})])).rejects.toMatchObject({code:'22023'});});
 it('reserva de IA é idempotente, limitada e não sobrescreve o editor',async()=>{const a=await create();const gid=crypto.randomUUID();const reserve=()=>q('SELECT rv_reservar($1,$2,1) AS r',[gid,a.id]);await expect(reserve()).rejects.toMatchObject({code:'P0002'});await db.exec('UPDATE mc_orcamentos SET max_chamadas_dia=1');expect((await reserve())[0].r.nova).toBe(true);expect((await reserve())[0].r.nova).toBe(false);await expect(q('SELECT rv_reservar($1,$2,1)',[crypto.randomUUID(),a.id])).rejects.toMatchObject({code:'MC409'});const d={variantes:[estruturaManual('hva','Proposta')],selecionada:null};await db.exec('SET ROLE authenticated');await expect(q("SELECT rv_concluir($1,'concluida',$2::jsonb,null,'deepseek',1,2)",[gid,JSON.stringify(d)])).rejects.toMatchObject({code:'42501'});await db.exec('RESET ROLE');expect((await q("SELECT rv_concluir($1,'concluida',$2::jsonb,null,'deepseek',1,2) AS ok",[gid,JSON.stringify(d)]))[0].ok).toBe(true);expect((await q("SELECT rv_concluir($1,'concluida',$2::jsonb,null,'deepseek',1,2) AS ok",[gid,JSON.stringify(d)]))[0].ok).toBe(false);expect((await q('SELECT documento FROM rv_roteiros WHERE id=$1',[a.id]))[0].documento.variantes).toEqual([]);expect(await q('SELECT estado FROM custos_ia WHERE origem_id=$1',['roteiro:'+gid])).toEqual([{estado:'concluida'}]);await expect(q('SELECT rv_reservar($1,$2,1)',[crypto.randomUUID(),a.id])).rejects.toMatchObject({code:'P0003'});});
 it('anon não executa criação, gravação nem reserva',async()=>{await db.exec('SET ROLE anon');await expect(create()).rejects.toMatchObject({code:'42501'});await db.exec('RESET ROLE');});
});

describe('reservas de refinamento',()=>{
 it('captura texto do servidor, partilha limite, repete o mesmo id sem cobrar e rejeita outro contexto',async()=>{
  await q('UPDATE mc_orcamentos SET max_chamadas_dia=100');const r=await create();const v=estruturaManual('hva','Roteiro');v.cenas.forEach(c=>{c.locucao='Texto para gravar';c.referencias=[1];});
  await q('SELECT rv_guardar($1,1,$2::jsonb,$3::jsonb)',[r.id,JSON.stringify(brief),JSON.stringify({variantes:[v],selecionada:v.id})]);
  const id=crypto.randomUUID();const args=[id,r.id,2,'trecho',v.id,v.cenas[0].id,'pergunta'];const sql='SELECT rv_reservar_contexto($1,$2,$3,$4,$5,$6,$7) AS r';
  const a=(await q(sql,args))[0].r;expect(a.nova).toBe(true);expect(a.geracao.contexto.variante).toEqual(v);expect((await q(sql,args))[0].r.nova).toBe(false);
  await expect(q(sql,[id,r.id,2,'trecho',v.id,v.cenas[1].id,'pergunta'])).rejects.toThrow('outro pedido');
  await expect(q(sql,[crypto.randomUUID(),r.id,2,'trecho',v.id,'inexistente','pergunta'])).rejects.toThrow('Secção');
  await q("SELECT rv_concluir($1,'erro',null,'Teste','modelo',0,0)",[id]);
  await q('UPDATE mc_orcamentos SET max_chamadas_dia=1');await expect(q(sql,[crypto.randomUUID(),r.id,2,'visual',v.id,null,'alternativa'])).rejects.toThrow('Limite diário');
 });
 it('recusa utilizador sem acesso e gravação de cliente na tabela de pedidos',async()=>{const r=await create();await db.exec("SET local.editor='false'");await expect(q('SELECT rv_reservar_contexto($1,$2,1)',[crypto.randomUUID(),r.id])).rejects.toThrow('Sem acesso');await db.exec("SET local.editor='true'");expect((await q("SELECT has_function_privilege('anon','rv_reservar_contexto(uuid,uuid,integer,text,text,text,text)','EXECUTE') AS ok"))[0].ok).toBe(false);expect((await q("SELECT has_table_privilege('authenticated','rv_geracoes','UPDATE') AS ok"))[0].ok).toBe(false);});
});
