import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {EditorRoteiro} from '@/features/roteiros/EditorRoteiro';
import type {ApiRoteiros} from '@/services/roteiros';
import {briefInicial,estruturaManual,type Roteiro,type GeracaoRoteiro} from '../../supabase/functions/_shared/roteiros/modelo';
const v=estruturaManual('hva','Roteiro de teste');v.cenas[0].locucao='Uma ideia para ler em voz alta.';v.cenas[0].visual='Uma imagem que não entra na cópia.';
const r:Roteiro={id:'id',project_id:'project',fonte:{tipo:'texto',titulo:'Notícia',texto:'A fonte original tem informação suficiente para esta validação de integração.',url:null},brief:briefInicial(),documento:{variantes:[v],selecionada:v.id},revisao:1,criado_em:new Date().toISOString(),atualizado_em:new Date().toISOString()};
function api():ApiRoteiros{return {listar:vi.fn().mockResolvedValue([structuredClone(r)]),obter:vi.fn().mockResolvedValue(structuredClone(r)),criar:vi.fn(),guardar:vi.fn().mockImplementation(async(id,rev,brief,documento)=>({...structuredClone(r),revisao:rev+1,brief,documento})),historico:vi.fn().mockResolvedValue([{...r,documento:{variantes:[],selecionada:null}}]),geracoes:vi.fn().mockResolvedValue([]),gerar:vi.fn().mockResolvedValue({id:'g',estado:'a_processar',criado_em:new Date().toISOString()})};}
const mount=(a:ApiRoteiros)=>render(<MemoryRouter initialEntries={['/estudio/roteiros/id']}><Routes><Route path="/estudio/roteiros/:id" element={<EditorRoteiro api={a} projectId="project"/>}/></Routes></MemoryRouter>);
afterEach(()=>{cleanup();vi.restoreAllMocks();});
describe('roteiros: ações do editor',()=>{
 it('guarda edição real, não gera ao abrir, e copia só a locução',async()=>{const a=api();const copy=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:copy}});mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);expect(a.gerar).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Texto revisto por mim.'}});expect(screen.getByText('Alterações por guardar')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Guardar versão'}));await waitFor(()=>expect(a.guardar).toHaveBeenCalledWith('id',1,r.brief,expect.objectContaining({variantes:[expect.objectContaining({cenas:expect.arrayContaining([expect.objectContaining({locucao:'Texto revisto por mim.'})])})]})));await screen.findByText('Guardado · versão 2');fireEvent.click(screen.getByRole('button',{name:'Copiar para BIGVU'}));await waitFor(()=>expect(copy).toHaveBeenCalledWith('Texto revisto por mim.'));});
 it('preserva texto quando a gravação falha, sem fingir sucesso',async()=>{const a=api();vi.mocked(a.guardar).mockRejectedValue(new Error('Conflito de versão'));mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Não perder esta edição.'}});fireEvent.click(screen.getByRole('button',{name:'Guardar versão'}));expect(await screen.findByRole('alert')).toHaveTextContent('Conflito de versão');expect(screen.getByDisplayValue('Não perder esta edição.')).toBeInTheDocument();expect(screen.getByText('Alterações por guardar')).toBeInTheDocument();});
 it('reordena, adiciona e remove trechos sem apagar a fonte',async()=>{const a=api();mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.click(screen.getByRole('button',{name:'Descer trecho 1'}));expect(screen.getByLabelText('2. Gancho')).toHaveValue(v.cenas[0].locucao);fireEvent.click(screen.getByRole('button',{name:'Adicionar trecho'}));expect(screen.getByLabelText('4. Novo trecho')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Remover trecho 4'}));expect(screen.queryByLabelText('4. Novo trecho')).not.toBeInTheDocument();expect(screen.getByText(r.fonte.texto)).toBeInTheDocument();});
 it('aplicar proposta grava nova opção e preserva a versão editada',async()=>{const a=api();const nova=estruturaManual('pas','Proposta');nova.cenas[0].locucao='Nova leitura.';const g:GeracaoRoteiro={brief:r.brief,id:'g',roteiro_id:r.id,estado:'concluida',resultado:{variantes:[nova],selecionada:nova.id},erro:null,revisao_base:1,criado_em:r.criado_em};vi.mocked(a.geracoes).mockResolvedValue([g]);mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.mouseDown(screen.getByRole('tab',{name:'Comparar propostas'}),{button:0});fireEvent.click(screen.getByRole('tab',{name:'Comparar propostas'}));fireEvent.click(await screen.findByRole('button',{name:'Aplicar e editar'}));await waitFor(()=>expect(a.guardar).toHaveBeenCalledWith('id',1,r.brief,{variantes:[v,nova],selecionada:nova.id}));expect(await screen.findByDisplayValue('Nova leitura.')).toBeInTheDocument();});
 it('não cobra sem confirmação e não chama IA duas vezes',async()=>{const a=api();mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.click(screen.getByRole('button',{name:'Gerar e comparar roteiros'}));expect(await screen.findByRole('alertdialog')).toBeInTheDocument();expect(a.gerar).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Gerar propostas'}));await waitFor(()=>expect(a.gerar).toHaveBeenCalledTimes(1));});
 it('regenera só o gancho com a abordagem escolhida e exige confirmação',async()=>{const a=api();mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.click(screen.getByRole('button',{name:'Regenerar com IA · Gancho'}));expect(a.gerar).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('radio',{name:'Uma pergunta'}));fireEvent.click(screen.getByRole('button',{name:'Gerar alternativas'}));await waitFor(()=>expect(a.gerar).toHaveBeenCalledWith(expect.any(String),expect.objectContaining({id:r.id}),{modo:'trecho',variante_id:v.id,cena_id:v.cenas[0].id,estilo:'pergunta'}));});
 it('aplica alternativa a uma nova versão e mantém valor e ação',async()=>{const a=api();const nova=estruturaManual('hva','Outro gancho');nova.cenas=[{...v.cenas[0],locucao:'Um novo gancho.',id:'nova-cena'}];const contexto={modo:'trecho' as const,variante_id:v.id,cena_id:v.cenas[0].id,variante:structuredClone(v)};const g:GeracaoRoteiro={contexto,brief:r.brief,id:'g',roteiro_id:r.id,estado:'concluida',resultado:{variantes:[nova],selecionada:nova.id},erro:null,revisao_base:1,criado_em:r.criado_em};vi.mocked(a.geracoes).mockResolvedValue([g]);mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.mouseDown(screen.getByRole('tab',{name:'Comparar propostas'}),{button:0});fireEvent.click(screen.getByRole('tab',{name:'Comparar propostas'}));fireEvent.click(await screen.findByRole('button',{name:'Usar esta alternativa'}));await waitFor(()=>expect(a.guardar).toHaveBeenCalledWith('id',1,r.brief,{variantes:[v,expect.objectContaining({id:nova.id,cenas:[expect.objectContaining({id:v.cenas[0].id,locucao:'Um novo gancho.'}),v.cenas[1],v.cenas[2]]})],selecionada:nova.id}));});
 it('mostra plano opcional e navega entre cenas sem IA',async()=>{const a=api();a.iaDisponivel=false;mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.mouseDown(screen.getByRole('tab',{name:'Preparar gravação'}),{button:0});fireEvent.click(screen.getByRole('tab',{name:'Preparar gravação'}));expect(await screen.findByRole('button',{name:'Preparar plano com IA'})).toBeDisabled();expect(screen.getByText('1 de 3 · Gancho')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Cena seguinte'}));expect(screen.getByText('2 de 3 · Valor')).toBeInTheDocument();expect(a.gerar).not.toHaveBeenCalled();});

 it('ativar a IA local não apaga uma edição pendente',async()=>{const a=api();a.iaDisponivel=false;const view=mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Edição por guardar.'}});view.rerender(<MemoryRouter initialEntries={['/estudio/roteiros/id']}><Routes><Route path="/estudio/roteiros/:id" element={<EditorRoteiro api={{...a,iaDisponivel:true}} projectId="project"/>}/></Routes></MemoryRouter>);expect(screen.getByDisplayValue('Edição por guardar.')).toBeInTheDocument();expect(a.obter).toHaveBeenCalledTimes(1);});

 it('desfaz remoção com o id original sem apagar outra edição',async()=>{const a=api();mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.click(screen.getByRole('button',{name:'Remover trecho 1'}));expect(screen.queryByLabelText('1. Gancho')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('1. Valor'),{target:{value:'Valor revisto depois da remoção.'}});fireEvent.click(screen.getByRole('button',{name:'Desfazer remoção'}));expect(screen.getByLabelText('1. Gancho')).toHaveValue(v.cenas[0].locucao);expect(screen.getByLabelText('2. Valor')).toHaveValue('Valor revisto depois da remoção.');fireEvent.click(screen.getByRole('button',{name:'Guardar alterações'}));await waitFor(()=>expect(a.guardar).toHaveBeenCalledWith('id',1,r.brief,expect.objectContaining({variantes:[expect.objectContaining({cenas:expect.arrayContaining([expect.objectContaining({id:v.cenas[0].id,locucao:v.cenas[0].locucao})])})]})));});
 it('retoma o mesmo pedido desconhecido e conserva a edição feita entretanto',async()=>{const a=api();vi.mocked(a.gerar).mockRejectedValueOnce(new Error('Resposta não confirmada'));mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.click(screen.getByRole('button',{name:'Regenerar com IA · Gancho'}));fireEvent.click(screen.getByRole('button',{name:'Gerar alternativas'}));await screen.findByText('Resposta não confirmada');fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Texto editado enquanto verifico o pedido.'}});fireEvent.click(screen.getByRole('button',{name:'Verificar pedido pendente'}));await waitFor(()=>expect(a.gerar).toHaveBeenCalledTimes(2));expect(vi.mocked(a.gerar).mock.calls[0]).toEqual(vi.mocked(a.gerar).mock.calls[1]);expect(screen.getByText('Alterações por guardar')).toBeInTheDocument();fireEvent.mouseDown(screen.getByRole('tab',{name:'Roteiro'}),{button:0});fireEvent.click(screen.getByRole('tab',{name:'Roteiro'}));expect(screen.getByLabelText('1. Gancho')).toHaveValue('Texto editado enquanto verifico o pedido.');expect(a.guardar).not.toHaveBeenCalled();});
 it('guarda com Ctrl+S sem repetir a gravação',async()=>{const a=api();mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Guardar pelo teclado.'}});fireEvent.keyDown(document,{key:'s',ctrlKey:true});fireEvent.keyDown(document,{key:'s',ctrlKey:true});await screen.findByText('Guardado · versão 2');expect(a.guardar).toHaveBeenCalledTimes(1);expect(screen.queryByRole('complementary',{name:'Alterações pendentes'})).not.toBeInTheDocument();});
 it('guarda antes de sair por um link e só navega após sucesso',async()=>{const a=api();render(<MemoryRouter initialEntries={['/estudio/roteiros/id']}><Routes><Route path="/estudio/roteiros/:id" element={<EditorRoteiro api={a} projectId="project"/>}/><Route path="/estudio/roteiros" element={<h1>Lista de roteiros</h1>}/></Routes></MemoryRouter>);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Guardar antes de sair.'}});fireEvent.click(screen.getByRole('link',{name:'Meus roteiros'}));expect(await screen.findByRole('alertdialog')).toHaveTextContent('Tens alterações por guardar');fireEvent.click(screen.getByRole('button',{name:'Guardar e sair'}));expect(await screen.findByRole('heading',{name:'Lista de roteiros'})).toBeInTheDocument();expect(a.guardar).toHaveBeenCalledTimes(1);});
 it('não sai nem apaga texto quando guardar e sair falha',async()=>{const a=api();vi.mocked(a.guardar).mockRejectedValue(new Error('Sem ligação à base de dados'));mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);fireEvent.change(screen.getByLabelText('1. Gancho'),{target:{value:'Preservar mesmo sem ligação.'}});fireEvent.click(screen.getByRole('link',{name:'Meus roteiros'}));fireEvent.click(await screen.findByRole('button',{name:'Guardar e sair'}));await waitFor(()=>expect(screen.getByRole('alertdialog')).toHaveTextContent('Sem ligação à base de dados'));fireEvent.click(screen.getByRole('button',{name:'Continuar a editar'}));expect(screen.getByLabelText('1. Gancho')).toHaveValue('Preservar mesmo sem ligação.');expect(screen.getByText('Alterações por guardar')).toBeInTheDocument();});
 it('mantém pelo menos uma estrutura selecionada',async()=>{const a=api();mount(a);await screen.findByDisplayValue(v.cenas[0].locucao);const checks=screen.getAllByRole('checkbox');fireEvent.click(checks[1]);fireEvent.click(checks[2]);expect(checks[0]).toBeChecked();expect(checks[0]).toBeDisabled();});

});
