// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { EdicaoRevista } from "./compose.server.ts";
export interface ContagemSeleccao {
    total: number;
    noEmail: number;
    extras: number;
    /** Verdadeiro quando há total fiável para mostrar números. */
    confirmada: boolean;
    /** Texto acima do botão, no fim de «Novidades da semana». */
    intro: string;
    /** Rótulo do botão que abre a edição online. */
    botao: string;
    /** Frase de fecho, antes da assinatura. */
    fecho: string;
    /** Texto do elo dentro da frase de fecho. */
    fechoElo: string;
}
/** «1 notícia» / «19 notícias». */
export declare function noticiasPlural(n: number): string;
export declare function contagemSeleccao(e: EdicaoRevista): ContagemSeleccao;
