// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
/** Parses the comma/newline separated list stored in `configuracoes`. */
export declare function lerListaDominios(valor: string | null | undefined): string[];
/** Returns blocked domains found in any URL inside the given content. */
export declare function encontrarDominiosBloqueados(conteudo: unknown, bloqueados: string[]): string[];
