// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
/** Translates backup failures into readable pt-PT copy for the panel. */
export declare function mensagemErroBackup(e: unknown): string;
