// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import { type DiferencaArtigo, type ArtigoCronica } from "./artigo-cronica.ts";
export interface ConfigFrederico {
    /** Definições não sensíveis, sempre disponíveis. */
    postType: string;
    status: "draft" | "publish";
    categoria: string | null;
    autor: number | null;
    timeoutMs: number;
    /** Credenciais — ausentes nesta fase. */
    siteUrl: string | null;
    utilizador: string | null;
    password: string | null;
}
export interface EstadoIntegracaoFrederico {
    configurada: boolean;
    /** Nunca inclui credenciais — apenas o que é seguro mostrar no editor. */
    postType: string;
    status: "draft" | "publish";
    categoria: string | null;
    motivo: string | null;
}
/** Estado da integração. Ausência de credenciais nunca é erro. */
export declare function obterEstadoIntegracaoFrederico(): Promise<EstadoIntegracaoFrederico>;
export interface ArtigoPreview {
    artigo: ArtigoCronica;
    problemas: string[];
    integracao: EstadoIntegracaoFrederico;
    /** `criar` na primeira publicação; `actualizar` quando já existe artigo. */
    operacao: "criar" | "actualizar";
    externalId: string | number | null;
    /** Proveniência visível no editor. */
    cronicaId: string | null;
}
/** Constrói (sem publicar) o artigo exacto que iria para FredericoCarvalho.pt. */
export declare function construirArtigoCronica(edicaoId: string): Promise<ArtigoPreview>;
/**
 * `hash_publicado` representa apenas a última versão confirmada publicamente
 * em FredericoCarvalho.pt. Enquanto o artigo estiver em rascunho o campo fica
 * a null — mesmo que já existisse um valor gravado indevidamente.
 */
export declare function hashPublicadoParaEstado(statusRemoto: string | null | undefined, hash: string | null): string | null;
/**
 * Contagem real de artigos com um dado slug. Só leitura — nunca cria,
 * actualiza nem apaga. Serve para provar unicidade antes de publicar.
 */
export interface ArtigoPorSlug {
    id: number;
    slug: string;
    status: string;
    titulo: string;
    link: string | null;
}
export declare function contarArtigosPorSlug(slug: string): Promise<{
    ok: boolean;
    slug: string;
    total: number;
    artigos: ArtigoPorSlug[];
    mensagem: string;
}>;
export interface DiagnosticoAutenticacao {
    ok: boolean;
    /** Nome público do utilizador — nunca a palavra-passe nem o header. */
    utilizador: string | null;
    id: number | null;
    podeEscrever: boolean;
    mensagem: string;
}
/** Confirma que as credenciais são aceites e que o utilizador pode escrever. */
export declare function verificarAutenticacao(cfg?: ConfigFrederico): Promise<DiagnosticoAutenticacao>;
export interface CategoriaCronicas {
    ok: boolean;
    id: number | null;
    nome: string | null;
    slug: string | null;
    mensagem: string;
}
/** Resolve a categoria «Crónicas» pelo slug. Nunca cria categorias. */
export declare function resolverCategoriaCronicas(cfg?: ConfigFrederico, sb?: SupabaseClient): Promise<CategoriaCronicas>;
export interface ArtigoConfirmado {
    id: number;
    status: string;
    titulo: string;
    slug: string;
    excerpt: string;
    /** Corpo tal como está guardado no WordPress — base da comparação editorial. */
    conteudo: string;
    conteudoTamanho: number;
    categorias: number[];
    autor: number | null;
    link: string | null;
}
/** Lê no WordPress o artigo escrito — nunca damos sucesso só pelo código HTTP. */
export declare function lerArtigo(cfg: ConfigFrederico, id: string | number): Promise<ArtigoConfirmado | null>;
export interface DiagnosticoRankMath {
    disponivel: boolean;
    /** Só verdadeiro quando existe rota de escrita com contrato declarado. */
    escritaSuportada: boolean;
    status: number | null;
    rotas: string[];
    /** Argumentos declarados pela rota de escrita — nunca adivinhados. */
    argumentos: string[];
    mensagem: string;
}
/**
 * Auditoria autenticada ao Rank Math.
 *
 * Só leitura: descobre as rotas do namespace e o contrato declarado da rota de
 * escrita de metadados. Não escreve nada e não adivinha campos internos.
 */
export declare function auditarRankMath(cfg?: ConfigFrederico): Promise<DiagnosticoRankMath>;
export interface ResultadoSeo {
    ok: boolean;
    escrito: string[];
    mensagem: string;
}
/**
 * Escreve os metadados SEO da crónica via Rank Math.
 *
 * Só é chamada depois de a auditoria confirmar a rota e o contrato. O canonical
 * é sempre a URL pública da crónica em FredericoCarvalho.pt — nunca a edição
 * Digital Sprint, que tem canónica própria.
 */
export declare function escreverSeoCronica(cfg: ConfigFrederico, postId: string | number, dados: {
    title: string;
    description: string;
    canonical: string;
}): Promise<ResultadoSeo>;
/**
 * Confirma que o artigo externo pertence mesmo a esta edição.
 *
 * Bloqueia (nunca escreve) quando: outra edição reclama o mesmo `external_id`,
 * o slug guardado difere do slug remoto, ou a URL guardada aponta para outro
 * artigo. Devolve `null` quando está tudo alinhado.
 */
export declare function guardaExternalId(sb: SupabaseClient, edicaoId: string, externalId: string | number, remoto: ArtigoConfirmado): Promise<string | null>;
export interface ResultadoPublicacao {
    ok: boolean;
    url: string | null;
    externalId: string | number | null;
    operacao: "criar" | "actualizar";
    mensagem: string;
    /** Estado do artigo no WordPress: `draft` nesta fase. */
    wpStatus?: string | null;
    confirmacao?: ArtigoConfirmado | null;
}
/**
 * Publica ou actualiza o artigo da crónica.
 *
 * Idempotência: a decisão POST/PUT é do servidor e depende exclusivamente da
 * existência de `destinos.cronica.external_id`. Nunca cria um segundo artigo
 * por retry, timeout ou nova edição do texto.
 */
export declare function publicarCronica(opts: {
    edicaoId: string;
    quem?: string | null;
}): Promise<ResultadoPublicacao>;
/** Retry — exactamente a mesma operação; o servidor volta a decidir criar/actualizar. */
export declare function repetirPublicacaoCronica(opts: {
    edicaoId: string;
    quem?: string | null;
}): Promise<ResultadoPublicacao>;
/**
 * Torna público o artigo que já existe em rascunho.
 *
 * Actua exclusivamente sobre `destinos.cronica.external_id`: nunca cria um
 * artigo, nunca faz POST na colecção. Se alguma verificação prévia falhar, não
 * é escrito nada.
 */
export declare function publicarArtigoCronica(opts: {
    edicaoId: string;
    quem?: string | null;
}): Promise<ResultadoPublicacao>;
/**
 * Actualiza o artigo já publicado.
 *
 * Contrato desta operação, diferente da fase de rascunho:
 *   • escreve sempre e apenas em `destinos.cronica.external_id`;
 *   • nunca envia `slug` — o permalink público é imutável após a publicação;
 *   • nunca envia `status` — não há forma de despublicar por engano;
 *   • confirma por leitura que ID e slug se mantiveram.
 */
export declare function actualizarArtigoCronica(opts: {
    edicaoId: string;
    quem?: string | null;
}): Promise<ResultadoPublicacao & {
    seo?: ResultadoSeo | null;
}>;
export interface ResultadoReconciliacao {
    ok: boolean;
    /** `true` quando o hash foi reescrito sem tocar no WordPress. */
    reconciliado: boolean;
    diferencas: DiferencaArtigo[];
    externalId: string | number | null;
    hash: string | null;
    mensagem: string;
}
/**
 * Reconcilia `destinos.cronica.hash_publicado` quando a regra de integridade
 * mudou mas o artigo remoto já contém a versão canónica.
 *
 * Nunca escreve no WordPress: só lê. Se existir qualquer diferença editorial
 * real, recusa e devolve o relatório — o caminho correcto é «Actualizar artigo».
 */
export declare function reconciliarHashCronica(opts: {
    edicaoId: string;
    quem?: string | null;
}): Promise<ResultadoReconciliacao>;
