// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
/** Mantém apenas parágrafos, quebras, negrito, itálico e sublinhado. */
export declare function htmlEditorialSeguro(valor: string | null | undefined): string;
/** Variante sem blocos, adequada a títulos e subtítulos. */
export declare function htmlEditorialInline(valor: string | null | undefined): string;
/** Texto simples para resumos, validações e versões sem HTML. */
export declare function textoDeHtmlEditorial(valor: string | null | undefined): string;
