// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export interface SinaisEdicao {
    /** `edicoes.estado` */
    estado: string;
    /** Estado do envelope do snapshot: `preparado`, `bloqueado` ou ausente. */
    snapshotEstado: string | null;
    /** Existe snapshot gravado. */
    temSnapshot: boolean;
    /** `destinos.web.estado` */
    destinoWeb: string;
}
export interface EstadoPublicacao {
    publica: boolean;
    enviada: boolean;
}
export declare function avaliarPublicacao(s: SinaisEdicao): EstadoPublicacao;
/** Um Brief só indexa se for Destaque, marcado indexável e de edição enviada. */
export declare function briefIndexavel(args: {
    tipo: "destaque" | "radar";
    indexavel: boolean;
    enviada: boolean;
    preview?: boolean;
}): boolean;
