// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { EdicaoRevista } from "./compose.server.ts";
export declare function montarTextoRevista(e: EdicaoRevista): string;
