// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const R: {
    /** Fundo à volta do cartão da edição. */
    readonly fundoExterior: "#E8E8E3";
    /** Papel da edição. */
    readonly fundoCartao: "#FAF9F5";
    /** Tinta principal (títulos, marca, blocos escuros). */
    readonly navy: "#171A21";
    /** Azul de acento. */
    readonly azul: "#0077B6";
    readonly azulSublinhado: "#9CD3EE";
    /** Fundo azul muito suave do cartão de serviço em destaque. */
    readonly azulSuave: "#EBF7FD";
    /** Corpo de texto. */
    readonly texto: "#494E58";
    /** Texto secundário e metadados. */
    readonly textoSec: "#626770";
    /** Painel claro (índice, rodapé). */
    readonly painel: "#EEEEE8";
    readonly filete: "#D7D9D1";
    readonly fileteClaro: "#E3E3DC";
    readonly lima: "#E7EF84";
    readonly escuro: "#171A21";
    readonly escuroFilete: "#434650";
    readonly escuroTexto: "#CCD0D8";
    readonly ferramentaFundo: "#F0F3FA";
    readonly ferramentaBorda: "#CDD2DF";
    readonly ferramentaBotaoBorda: "#949BAA";
    readonly amarelo: "#FFDC00";
    readonly amareloFilete: "#9F8900";
    readonly branco: "#FFFFFF";
};
export declare const SANS = "Arial,Helvetica,sans-serif";
export declare const BLACK = "Arial Black,Arial Bold,Arial,Helvetica,sans-serif";
export declare const SERIF = "Georgia,'Times New Roman',serif";
/** Rótulo do CTA da recomendação, consoante o tipo escolhido. */
export declare function ctaRecomendacao(tipo: string): string;
export declare const TIPOS_RECOMENDACAO: readonly ["Podcast", "Ferramenta", "Livro", "Curso", "Recurso", "Evento", "Outro"];
/** Rótulo por omissão do botão de uma notícia em foco. */
export declare const CTA_NOTICIA_PADRAO = "Ler a not\u00EDcia";
