// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { BriefDaEdicao, TipoBrief } from "../../newsletter-engine/revista/brief/tipos.ts";
export type { BriefDaEdicao, TipoBrief };
export interface EdicaoParaBriefs {
    id: string;
    numero: number;
    estado: string;
    assunto: string | null;
}
export interface NoticiaParaBrief {
    id: string;
    titulo: string;
    url: string | null;
    categoria: string;
}
/** Edições Revista disponíveis no painel de Briefs. */
export declare const listarEdicoesBriefFn: import("../_shim/start.ts").NlServerFn<void, EdicaoParaBriefs[]>;
/** Notícias aprovadas da edição — universo a partir do qual se cria um Brief. */
export declare const listarNoticiasParaBriefFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
}, NoticiaParaBrief[]>;
/** Briefs já associados a uma edição. */
export declare const listarBriefsDaEdicaoFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
}, BriefDaEdicao[]>;
/** Cria (ou reutiliza) o Brief de uma notícia e associa-o à edição. */
export declare const criarBriefFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
    noticiaId: string;
    papel: TipoBrief;
}, {
    criado: boolean;
    slug: string;
    reutilizado: boolean;
}>;
/** Retira o Brief desta edição (o Brief em si mantém-se). */
export declare const removerBriefDaEdicaoFn: import("../_shim/start.ts").NlServerFn<{
    briefId: string;
    edicaoId: string;
}, {
    ok: boolean;
}>;
/** Grava o conteúdo editorial escrito à mão (sem IA nesta fase). */
export declare const guardarConteudoBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
    em30: string[];
    porqueInteressa: Array<{
        rotulo: string;
        texto: string;
    }>;
    leitura: string;
    fonteUrl: string;
    publisher: string;
}, {
    estado: import("../../newsletter-engine/revista/brief/tipos.ts").EstadoBrief;
    aprovada: boolean;
}>;
/** Aprovação explícita da leitura de um Destaque. */
export declare const aprovarLeituraBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
    texto: string;
}, {
    estado: import("../../newsletter-engine/revista/brief/tipos.ts").EstadoBrief;
    aprovadaEm: string | null;
}>;
/** Volta a pôr a leitura por rever. */
export declare const revogarLeituraBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
}, {
    estado: import("../../newsletter-engine/revista/brief/tipos.ts").EstadoBrief;
}>;
declare const COMPONENTES: readonly ["tudo", "em_30_segundos", "porque_interessa", "leitura_sugerida"];
declare const INTENCOES: readonly ["normal", "mais_pragmatico", "mais_curto", "menos_opinativo", "outro_angulo", "simplificar"];
export type ComponenteBriefUi = (typeof COMPONENTES)[number];
export type IntencaoBriefUi = (typeof INTENCOES)[number];
export interface ResultadoGeracaoUi {
    estado: string;
    bloqueado: boolean;
    motivos: string[];
    erro: string | null;
}
/** Gera ou regenera o Brief (tudo ou apenas uma peça). */
export declare const gerarBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
    componente?: string;
    intencao?: string;
}, ResultadoGeracaoUi>;
/** Reformula quando a proximidade com o original bloqueou o Brief. */
export declare const reformularBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
}, ResultadoGeracaoUi>;
/** Nova passagem de verificação, sem reescrever texto. */
export declare const reverificarBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
}, ResultadoGeracaoUi>;
export interface EstadoBriefEdicao {
    briefId: string;
    noticiaId: string | null;
    papel: TipoBrief;
    estado: string;
    rotulo: string;
    aprovada: boolean;
    titulo: string;
    slug: string;
    fonteUrl: string | null;
    fontePublisher: string | null;
    em30: string[];
    porqueInteressa: Array<{
        rotulo: string;
        texto: string;
    }>;
    leitura: string;
    pullQuote: string;
    motivos: string[];
    precisaAtencao: boolean;
    erro: string | null;
    actualizadoEm: string;
}
/** Estado dos Briefs de uma edição — o que o Editor Revista precisa de saber. */
export declare const estadoBriefsDaEdicaoFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
}, EstadoBriefEdicao[]>;
/** Acompanha a escolha editorial: Destaque, Radar ou fora do email. */
export declare const sincronizarBriefPapelFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
    noticiaId: string;
    papel: string | null;
}, {
    briefId: string | null;
    criado: boolean;
}>;
/** Autosave do texto da leitura em revisão. */
export declare const guardarLeituraBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
    texto: string;
}, {
    estado: import("../../newsletter-engine/revista/brief/tipos.ts").EstadoBrief;
    aprovada: boolean;
    revogou: boolean;
}>;
/**
 * Reconcilia todos os Briefs de uma edição com as escolhas já feitas em
 * «A Atualidade». Idempotente — serve para edições anteriores a esta fase.
 */
export declare const sincronizarBriefsDaEdicaoFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
}, {
    sincronizados: number;
}>;
/** Identidade editorial pública do Brief: título canónico e tese. */
export declare const guardarIdentidadeBriefFn: import("../_shim/start.ts").NlServerFn<{
    id: string;
    tituloEditorial: string;
    teseEditorial: string;
}, {
    ok: true;
}>;
