// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
/**
 * A partir de um URL (site ou feed), descobre feeds RSS/Atom válidos.
 * Devolve nome sugerido (título do site) e até 6 candidatos com título e nº itens.
 */
export declare const descobrirFeed: import("../_shim/start.ts").NlServerFn<{
    url: string;
}, {
    ok: false;
    erro: string;
    nomeSugerido: string;
    candidatos: {
        url: string;
        titulo: string;
        total: number;
        tipo: "rss" | "html";
    }[];
} | {
    ok: true;
    nomeSugerido: string;
    candidatos: {
        url: string;
        titulo: string;
        total: number;
        tipo: "rss" | "html";
    }[];
    erro?: undefined;
}>;
/**
 * Testa um feed RSS/Atom sem escrever nada.
 * Devolve o total de itens e os 3 mais recentes para pré-visualização.
 */
export declare const testarFeed: import("../_shim/start.ts").NlServerFn<{
    url: string;
}, {
    ok: boolean;
    erro: string;
    total: number;
    ultimos: Array<{
        titulo: string;
        url: string;
        publicado: number;
    }>;
} | {
    ok: boolean;
    total: number;
    ultimos: {
        titulo: string;
        url: string;
        publicado: number;
    }[];
    erro?: undefined;
}>;
export declare const correrCuradoriaAgora: import("../_shim/start.ts").NlServerFn<void, {
    ok: boolean;
    inseridas: number;
    fontes_activas: number;
    candidatos: number;
    duracao_ms: number;
}>;
/** Corre a curadoria só para uma fonte, imediatamente. */
export declare const correrFonteAgora: import("../_shim/start.ts").NlServerFn<{
    id: string;
}, {
    ok: boolean;
    inseridas: number;
    fontes_activas: number;
    candidatos: number;
    duracao_ms: number;
}>;
/** Activa/desactiva várias fontes de uma vez. */
export declare const alternarFontesEmLote: import("../_shim/start.ts").NlServerFn<{
    ids: string[];
    activa: boolean;
}, {
    ok: boolean;
    afectadas: number;
}>;
