// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const encurtarDescricao: import("../_shim/start.ts").NlServerFn<unknown, {
    descricao: string;
    alterada: boolean;
}>;
