// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const previewEdicaoFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    destino?: "email" | "wordpress";
}, {
    ok: true;
    destino: "wordpress";
    html: string;
    resumo: string;
} | {
    ok: true;
    destino: "email";
    html: string;
    resumo: string | undefined;
}>;
export declare const sincronizarRascunhoFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    lista_ids: string[];
}, {
    ok: boolean;
    campanhas: import("../../newsletter-engine/sincronizar-egoi.server.ts").ResultadoSync[];
    sucessos: number;
    falhas: number;
    mensagem: string;
}>;
export declare const dispararEgoiFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    lista_ids: string[];
    confirmacao_numero?: number;
}, {
    ok: boolean;
    modo: "teste" | "real";
    resultados: import("../../newsletter-engine/envio.server.ts").ResDisparo[];
    sucessos: number;
    falhas: number;
    mensagem: string;
}>;
/** Fase 1 do envio: prepara (cria/actualiza) as campanhas de todas as listas. */
export declare const prepararEnvioFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    lista_ids: string[];
    confirmacao_numero?: number;
    publicar_conteudos?: boolean;
}, {
    ok: true;
    modo: "teste" | "real";
    edicao: {
        numero: number;
        assunto: string;
    };
    listas: import("../../newsletter-engine/envio.server.ts").ListaPreparada[];
}>;
/** Fase 2 do envio: dispara uma lista já preparada. */
export declare const dispararListaFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    lista_id: string;
}, import("../../newsletter-engine/envio.server.ts").ResDisparo>;
/** Repete apenas uma lista que falhou (prepara + dispara). */
export declare const repetirListaFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    lista_id: string;
}, import("../../newsletter-engine/envio.server.ts").ResDisparo>;
/** Pergunta à E-goi o estado real das campanhas e alinha a base de dados. */
export declare const reconciliarEdicaoFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
}, {
    ok: true;
    actualizadas: Array<{
        lista_id: string;
        lista_nome: string;
    }>;
    por_confirmar: number;
    fechada: boolean;
}>;
/** Fase 3 do envio: liberta o bloqueio e fecha a edição. */
export declare const finalizarEnvioFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    lista_ids: string[];
    adiar_fecho?: boolean;
}, {
    ok: true;
    fechada: boolean;
    aguarda_confirmacao?: undefined;
} | {
    ok: true;
    fechada: boolean;
    aguarda_confirmacao: number;
}>;
export declare const publicarWordpressFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
}, {
    ok: true;
    post_id: number;
    post_url: string;
    status: string;
    actualizada: boolean;
    mensagem: string;
}>;
/** Agenda o envio de uma edição (apenas admin). */
export declare const agendarEnvioFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
    agendado_para: string;
    lista_ids: string[];
    wordpress: boolean;
}, {
    ok: true;
    agendado_para: string;
}>;
/** Cancela o agendamento de uma edição (apenas admin). */
export declare const cancelarAgendamentoFn: import("../_shim/start.ts").NlServerFn<{
    edicao_id: string;
}, {
    ok: true;
}>;
