// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { DeepSeekUsage } from "./deepseek.server.ts";
import type { IaResultado } from "./ia-extractor.server.ts";
export type RegistarUso = (u: {
    modelo: string;
    usage: DeepSeekUsage;
    origem: string;
}) => void | Promise<void>;
export interface EntradaExtraccao {
    titulo: string;
    descricao: string;
    url?: string | null;
    /** Material já disponível (ex.: corpo do email); evita ir à rede. */
    corpoConhecido?: string;
    /** Quando falso, não vai buscar a página original. */
    lerCorpo?: boolean;
    /** Origem registada em `ia_uso` para a extracção. */
    origemUso?: string;
}
export interface ResultadoExtraccao {
    ia: IaResultado | null;
    titulo: string;
    descricao: string;
    /** Texto do artigo lido (vazio quando não foi possível). */
    corpo: string;
    /** A descrição continua a repetir o título depois da reescrita. */
    repete: boolean;
    /** Causa real quando a IA não devolveu resultado (null quando correu bem). */
    motivo: string | null;
}
/** Uma única tentativa de reescrita quando a descrição repete o título. */
export declare function corrigirDescricaoRepetida(args: {
    titulo: string;
    descricao: string;
    corpo?: string;
}, registarUso?: RegistarUso): Promise<{
    descricao: string;
    repete: boolean;
    reescrita: boolean;
}>;
/**
 * Lê o artigo (quando há URL), extrai a notícia com a IA e garante que a
 * descrição acrescenta informação ao título. Nunca lança por causa da leitura
 * do artigo: sem corpo, segue com o material que houver.
 */
export declare function extrairNoticiaComCorpo(entrada: EntradaExtraccao, registarUso?: RegistarUso): Promise<ResultadoExtraccao>;
