// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type FerramentaSugerida = {
    id: string;
    nome: string;
    url: string;
    descricao: string | null;
    descricao_original?: string | null;
    emoji?: string | null;
    cor?: string | null;
    categoria: string | null;
    remetente: string | null;
    assunto_origem: string | null;
    fonte_email_id: string | null;
    fonte_directorio_id?: string | null;
    estado: "pendente" | "aprovada" | "rejeitada" | "arquivada";
    aprovada_em: string | null;
    criado_em: string;
    edicao_aprovada_id?: string | null;
    edicao_aprovada_numero?: number | null;
};
export type FiltroEstadoFerramenta = "pendente" | "aprovada" | "rejeitada" | "arquivada" | "todas";
export declare const listarFerramentas: import("../_shim/start.ts").NlServerFn<{
    estado?: FiltroEstadoFerramenta;
} | undefined, {
    ferramentas: FerramentaSugerida[];
    contagens: {
        pendente: number;
        aprovada: number;
        rejeitada: number;
        arquivada: number;
        total: number;
    };
}>;
export declare const actualizarEstadoFerramenta: import("../_shim/start.ts").NlServerFn<{
    id: string;
    estado: "pendente" | "aprovada" | "rejeitada" | "arquivada";
}, {
    ok: true;
}>;
export declare const apagarFerramenta: import("../_shim/start.ts").NlServerFn<{
    id: string;
}, {
    ok: true;
}>;
export declare const listarFerramentasDoEmail: import("../_shim/start.ts").NlServerFn<{
    emailId: string;
}, FerramentaSugerida[]>;
/** Aprova uma sugestão E insere-a no primeiro slot livre (1 ou 2) da
 *  edição em rascunho mais recente. Devolve o id da nova ferramenta_semana
 *  e o número da edição alvo. */
export declare const aprovarFerramentaParaRascunho: import("../_shim/start.ts").NlServerFn<{
    id: string;
    edicao_id?: string;
}, {
    ok: true;
    edicao_numero: number;
    posicao: 1 | 2;
    template_version: string;
} | {
    ok: false;
    motivo: string;
}>;
/** Edições em rascunho que podem receber uma ferramenta, com o formato
 *  (Clássico/Revista) e os lugares (1 e 2) ainda livres. */
export declare const listarEdicoesDestinoFerramenta: import("../_shim/start.ts").NlServerFn<Record<string, never> | undefined, {
    id: string;
    numero: number;
    template_version: string;
    livres: number;
}[]>;
/** Rejeita a ferramenta E bane-a por domínio E por nome normalizado,
 *  para que a curadoria automática não a volte a sugerir a partir de
 *  outra fonte com URL diferente. */
export declare const rejeitarFerramentaComBan: import("../_shim/start.ts").NlServerFn<{
    id: string;
}, {
    ok: true;
    dominio: string | null;
    nome_norm: string | null;
}>;
/** Contagem barata de sugestões arquivadas — usado pela sugestão suave
 *  na secção Ferramentas da Semana do editor. */
export declare const contarFerramentasArquivadas: import("../_shim/start.ts").NlServerFn<void, {
    total: number;
}>;
