// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
type Admin = SupabaseClient<any, any, any>;
export declare const CHAVE_MODO_MANUAL = "curadoria_modo_manual";
/** Items older than this are never interpreted: the newsletter needs current news. */
export declare const DIAS_MAX_PROCESSAR = 7;
export type ItemFila = {
    origem: "rss" | "email";
    fonte_id?: string | null;
    fonte_nome?: string | null;
    fonte_grupo?: string | null;
    email_recebido_id?: string | null;
    titulo: string;
    url?: string | null;
    url_norm?: string | null;
    descricao?: string;
    publicado_em?: string;
};
/** A recolha automática deve apenas guardar em fila (sem IA)? */
export declare function modoManualActivo(admin: Admin): Promise<boolean>;
export declare function definirModoManual(admin: Admin, manual: boolean): Promise<void>;
/** Insere candidatos na fila, ignorando os que já lá estão (url_norm único). */
export declare function enfileirar(admin: Admin, itens: ItemFila[]): Promise<number>;
/** Itens com mais de estes dias podem ser apagados da fila (pré-definição). */
export declare const DIAS_LIMPEZA_FILA = 20;
export type ContagemFila = {
    total: number;
    rss: number;
    email: number;
    falhados: number;
    antigas: number;
    mais_antigo: string | null;
    mais_recente: string | null;
};
export declare function contarFila(admin: Admin): Promise<ContagemFila>;
/**
 * Apaga itens da fila com mais de `dias` dias (pré-definição: 20).
 * Só toca em itens à espera ou falhados — nunca em itens já processados.
 */
export declare function limparFilaAntiga(admin: Admin, opcoes: {
    dias?: number;
    quem: string;
}): Promise<{
    apagados: number;
}>;
export type ResultadoLote = {
    ok: boolean;
    bloqueado?: boolean;
    processados: number;
    noticias: number;
    ferramentas: number;
    descartados: number;
    falhados: number;
    restantes: number;
    detalhes: Array<{
        titulo: string;
        resultado: string;
    }>;
};
/**
 * Processa até `limite` itens da fila, dos mais recentes para os mais antigos.
 * Cada item é marcado no momento em que termina, para que uma nova corrida
 * nunca repita trabalho já feito.
 */
export declare function processarLote(admin: Admin, opcoes: {
    limite: number;
    quem: string;
}): Promise<ResultadoLote>;
export {};
