// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
/** Quantos itens estão à espera de ser interpretados. */
export declare const contarFilaCuradoria: import("../_shim/start.ts").NlServerFn<void, {
    modo_manual: boolean;
    total: number;
    rss: number;
    email: number;
    falhados: number;
    antigas: number;
    mais_antigo: string | null;
    mais_recente: string | null;
}>;
/** Processa um lote da fila (10/20/30/50), dos mais recentes para os mais antigos. */
export declare const processarFilaCuradoria: import("../_shim/start.ts").NlServerFn<{
    limite: number;
}, import("./fila-curadoria.server.ts").ResultadoLote>;
/** Devolve itens falhados à fila para nova tentativa. */
export declare const retomarFalhadosCuradoria: import("../_shim/start.ts").NlServerFn<void, {
    retomados: number;
}>;
/** Liga ou desliga o modo manual da recolha. */
export declare const definirModoManualCuradoria: import("../_shim/start.ts").NlServerFn<{
    manual: boolean;
}, {
    ok: boolean;
    manual: boolean;
}>;
/** Apaga itens da fila com mais de N dias (pré-definição: 20). */
export declare const limparFilaAntigaCuradoria: import("../_shim/start.ts").NlServerFn<{
    dias?: number;
}, {
    apagados: number;
}>;
