// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export { mapCategoria } from "../edge-shared/ia-limpeza.ts";
import { type DeepSeekUsage } from "./deepseek.server.ts";
export type IaResultado = {
    categoria?: string;
    titulo?: string;
    descricao?: string;
    fonte?: string;
    url?: string;
};
export type ChamadaIA = {
    resultado: IaResultado | null;
    modelo: string;
    usage: DeepSeekUsage;
};
/** Instrução de correcção quando a descrição saiu parecida com o título. */
export declare const PROMPT_REESCRITA_DESCRICAO = "\u00C9s editor da newsletter Digital Sprint, em portugu\u00EAs de Portugal.\n\nRecebes o t\u00EDtulo de uma not\u00EDcia, uma descri\u00E7\u00E3o que ficou demasiado parecida com esse t\u00EDtulo e (quando existe) o corpo do artigo.\n\nReescreve APENAS a descri\u00E7\u00E3o:\n- 18 a 30 palavras, uma ou duas frases completas, factual e objectiva.\n- Tem de acrescentar o que o t\u00EDtulo n\u00E3o diz: n\u00FAmero, data ou prazo, quem \u00E9 afectado, condi\u00E7\u00E3o, limita\u00E7\u00E3o ou consequ\u00EAncia pr\u00E1tica.\n- N\u00E3o repitas a estrutura nem as palavras fortes do t\u00EDtulo.\n- Nunca inventes dados que n\u00E3o estejam no material recebido.\n- Sem emojis, sem retic\u00EAncias, sem prefixos (\"Descri\u00E7\u00E3o:\", \"Resumo:\").\n\nDevolve APENAS JSON v\u00E1lido: {\"descricao\": \"...\"}";
export declare function chamarIaExtrator(bloco: string, urlManual: string | undefined, corpoArtigo?: string): Promise<ChamadaIA>;
export type ChamadaDescricao = {
    descricao: string;
    modelo: string;
    usage: DeepSeekUsage;
};
/** Segunda passagem: pede uma descrição que complemente o título. */
export declare function reescreverDescricao(args: {
    titulo: string;
    descricao: string;
    corpoArtigo?: string;
}): Promise<ChamadaDescricao>;
