// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const gerarMinhaLeitura: import("../_shim/start.ts").NlServerFn<unknown, {
    leitura: string;
    palavras: number;
}>;
