// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type { FotoPexels } from "./pexels-tipos.ts";
import type { FotoPexels } from "./pexels-tipos.ts";
/** Pesquisa fotografias no Pexels (a chave nunca sai do servidor). */
export declare const pesquisarPexelsFn: import("../_shim/start.ts").NlServerFn<{
    termo: string;
    pagina?: number;
}, {
    fotos: FotoPexels[];
    erro?: string;
}>;
/** Copia uma foto do Pexels para o armazenamento e devolve o URL público. */
export declare const importarPexelsFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
    url: string;
}, {
    url: string;
}>;
/** Guarda uma imagem carregada do computador (base64) e devolve o URL público. */
export declare const carregarImagemFn: import("../_shim/start.ts").NlServerFn<{
    edicaoId: string;
    base64: string;
    tipo: string;
}, {
    url: string;
}>;
/**
 * Devolve uma imagem em base64 para recorte no browser (evita bloqueios CORS).
 * Só aceita http(s) e imagens até 10 MB.
 */
export declare const obterImagemBase64Fn: import("../_shim/start.ts").NlServerFn<{
    url: string;
}, {
    base64: string;
    tipo: string;
}>;
