// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
/** URL pública estável para uma imagem guardada no armazenamento editorial. */
export declare function urlImagemEditorial(backendUrl: string, caminho: string): string;
/**
 * Converte URLs da antiga aplicação para o endpoint editorial atual.
 * URLs externas e URLs já atuais permanecem inalteradas.
 */
export declare function normalizarUrlImagemEditorial(url: string, backendUrl: string): string;
