// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const MAX_CORPO = 8000;
/** Extrai o corpo do artigo a partir do HTML de uma página. */
export declare function extrairCorpoArtigo(html: string): string;
export interface ArtigoLido {
    corpo: string;
    ok: boolean;
    motivo?: string;
}
/**
 * Vai buscar a página e devolve o corpo do artigo. Limite de tempo curto:
 * uma fonte lenta nunca pode travar o processamento de um lote.
 */
export declare function lerArtigo(url: string | null | undefined): Promise<ArtigoLido>;
