// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type TecnicaAssunto = "curiosidade" | "dado_concreto" | "cronica";
export interface SugestaoAssunto {
    texto: string;
    preheader: string;
    tecnica: TecnicaAssunto;
    caracteres: number;
}
export declare const sugerirAssunto: import("../_shim/start.ts").NlServerFn<unknown, {
    sugestoes: SugestaoAssunto[];
}>;
