// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export interface SugestaoOrganizacao {
    id: string;
    titulo: string;
    categoria: string | null;
    destaque_proposto: boolean;
    destino_proposto: "news" | "site";
    justificacao: string;
    destaque_actual: boolean;
    destino_actual: "news" | "site";
}
export interface SugerirOrganizacaoResultado {
    ok: boolean;
    motivo?: string;
    aviso?: string;
    sugestoes: SugestaoOrganizacao[];
}
interface Input {
    edicaoId: string;
}
export declare const sugerirOrganizacaoEdicao: import("../_shim/start.ts").NlServerFn<Input, SugerirOrganizacaoResultado>;
export {};
