// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type Editor } from "./link-rastreio.ts";
export type ConsultaPreparada = {
    tituloEn: string;
    keywords: string[];
    editor: Editor | null;
    queries: string[];
    queryGoogle: string;
};
/**
 * Semelhança 0-1 entre dois títulos, combinando sobreposição de palavras
 * e de trigramas. Funciona razoavelmente entre línguas por causa das
 * entidades próprias (marcas, números) que se mantêm iguais.
 */
export declare function semelhancaTitulo(a: string, b: string): number;
/** Melhor semelhança contra vários textos de referência (pt + en). */
export declare function melhorSemelhanca(candidato: string, referencias: string[]): number;
/**
 * Constrói a cascata de queries. A IA é opcional: se falhar, usamos o título
 * em pt-PT como estava antes (comportamento actual, degradado mas funcional).
 */
export declare function prepararConsulta(titulo: string, descricao: string | null, urlActual: string | null): Promise<ConsultaPreparada>;
