// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export interface FotoPexels {
    id: number;
    previewUrl: string;
    originalUrl: string;
    alt: string;
    autor: string;
    autorUrl: string;
    largura: number;
    altura: number;
}
