// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type PropostaPecas } from "../../newsletter-engine/revista/pecas-proposta.ts";
export type { PropostaPecas };
export declare const proporPecasCronicaFn: import("../_shim/start.ts").NlServerFn<unknown, PropostaPecas>;
