// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { FotoPexels } from "./pexels-tipos.ts";
export declare const MIN_CARACTERES_CRONICA = 200;
export interface PropostaApresentacaoResultado {
    assinatura: string;
    titulo: string;
    subtitulo: string;
    lede: string;
    excerto: string;
    pullQuote: string;
    momento: {
        etiqueta: string;
        valor: string;
        descricao: string;
    };
    momentoRejeitado: boolean;
    imagem: {
        alt: string;
        termo: string;
        escolhida: FotoPexels | null;
        alternativas: FotoPexels[];
    };
    avisos: string[];
}
export declare const proporApresentacaoFn: import("../_shim/start.ts").NlServerFn<unknown, PropostaApresentacaoResultado>;
