// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const AMBITOS_RECOMECO: readonly ["noticias", "cronica", "blocos", "assunto", "briefs"];
export type AmbitoRecomeco = (typeof AMBITOS_RECOMECO)[number];
export declare const recomecarEdicaoFn: import("../_shim/start.ts").NlServerFn<unknown, {
    ok: boolean;
    numero: any;
}>;
