// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
export type ResultadoReprocessamento = {
    ok: true;
    noticias_inseridas: number;
    ferramentas_inseridas: number;
    formato: string;
    usou_fallback: boolean;
    motivo_sem_resultado: string | null;
};
/**
 * Corre o pipeline sobre um email já guardado.
 * `forcar` ignora o estado `activa` da fonte — é o comportamento correcto para
 * uma acção manual explícita de admin.
 */
export declare function reprocessarEmailGuardado(supabase: SupabaseClient<any, any, any>, emailId: string, quem: string, forcar: boolean): Promise<ResultadoReprocessamento>;
