// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const RESUMO_PODCAST_MAX = 200;
/** Remove links, emojis e aspas, colapsa espaços e corta em ~200 caracteres numa fronteira de palavra. */
export declare function limparResumoPodcast(texto: string | null | undefined): string;
