// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { PaginaEdicaoPublica, ResumoEdicaoPublica, GrupoAtualidades, VizinhaPublica } from "../../newsletter-engine/revista/publicacao.server.ts";
export type { PaginaEdicaoPublica, ResumoEdicaoPublica, GrupoAtualidades, VizinhaPublica };
/** Base absoluta das edições públicas (`configuracoes.edicoes_base_url`). */
export declare const baseUrlEdicoesFn: import("../_shim/start.ts").NlServerFn<void, string>;
/** Arquivo: todas as edições Revista publicadas, mais recente primeiro. */
export declare const listarEdicoesPublicasFn: import("../_shim/start.ts").NlServerFn<void, ResumoEdicaoPublica[]>;
/** Edição pública por número. `null` quando não existe ou não está publicada. */
export declare const obterEdicaoPublicaFn: import("../_shim/start.ts").NlServerFn<{
    numero: number;
}, PaginaEdicaoPublica | null>;
