// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type ItemFeed = {
    titulo: string;
    url: string;
    descricao: string;
    publicado: number;
};
export declare function parseFeed(xml: string): ItemFeed[];
export declare function lerFeed(url: string, timeoutMs?: number): Promise<ItemFeed[]>;
