// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const Route: {
    options: {
        server: {
            handlers: {
                POST: ({ request }: import("../_shim/router.ts").HookHandlerCtx) => Promise<Response>;
            };
        };
    };
};
