// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const supabaseAdmin: import("npm:@supabase/supabase-js@2.57.4").SupabaseClient<any, "public", "public", any, any>;
