// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export interface HookHandlerCtx {
    request: Request;
}
export type HookHandler = (ctx: HookHandlerCtx) => Promise<Response> | Response;
export interface HookRouteOptions {
    server?: {
        handlers?: Partial<Record<"GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS", HookHandler>>;
    };
}
export declare function createFileRoute<P extends string>(_path: P): <O extends HookRouteOptions>(options: O) => {
    options: O;
};
