// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type TarifaModelo = {
    /** USD por 1M tokens de entrada com acerto de cache. */
    cacheHit: number;
    /** USD por 1M tokens de entrada sem acerto de cache. */
    cacheMiss: number;
    /** USD por 1M tokens de saída. */
    saida: number;
};
export type PrecoModelo = {
    pico: TarifaModelo;
    foraPico: TarifaModelo;
};
/** Data a partir da qual esta tabela de preços passou a ser aplicada. */
export declare const PRECOS_EM_VIGOR_DESDE = "2026-09-10";
/** Preços por 1M tokens (tarifa de pico; fora de pico é metade). */
export declare const PRECOS_DEEPSEEK: Record<string, PrecoModelo>;
/** Nomes antigos aceites pela DeepSeek, servidos e facturados como o modelo actual. */
export declare const ALIAS_MODELOS: Record<string, string>;
/** Devolve o nome canónico do modelo (resolve nomes antigos). */
export declare function modeloCanonico(modelo: string): string;
/** Indica se existe tabela de preços para este modelo. */
export declare function precoConhecido(modelo: string): boolean;
/** Verdadeiro se o instante indicado cai em horário de pico da DeepSeek. */
export declare function ehHorarioPico(quando: Date): boolean;
/** Tarifa aplicável a um modelo num dado instante, ou null se o preço for desconhecido. */
export declare function tarifaAplicavel(modelo: string, quando: Date): TarifaModelo | null;
/**
 * Custo em USD de uma chamada.
 * `quando` permite recalcular registos antigos; por omissão usa o instante actual.
 * Modelos sem preço conhecido devolvem 0 — usa `precoConhecido()` para os distinguir.
 */
export declare function custoUsd(modelo: string, cacheHit: number, cacheMiss: number, saida: number, quando?: Date | string): number;
export declare function extrairTokens(usage: unknown): {
    cacheHit: number;
    cacheMiss: number;
    saida: number;
};
