// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { DadosEdicao } from "./gerar-html-newsletter.server.ts";
export declare function montarTexto(d: DadosEdicao): string;
