// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type HtmlWordpress } from "./gerar-html-wordpress.server.ts";
export declare function gerarHtmlEdicaoWeb(edicaoId: string): Promise<HtmlWordpress>;
