// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
declare const BG_PAGINA = "#EEF1F5";
declare const BG_CARTAO = "#FFFFFF";
declare const INK = "#0F172A";
declare const INK_MED = "#334155";
declare const INK_SEC = "#475569";
declare const TENUE = "#94A3B8";
declare const TENUE_2 = "#B0B7C3";
declare const DIVISOR = "#F1F5F9";
declare const PRIMARIA = "#6366F1";
declare const SOMBRA = "box-shadow:0 1px 3px rgba(15,23,42,0.06);";
declare const AVATAR_URL = "https://newsletter-digital-sprint.lovable.app/__l5e/assets-v1/64e62b56-bcaf-4d4a-b6d3-d80d1568af05/frederico-avatar.png";
declare const MEDALHAO_GRADIENTES: string[];
declare function esc(s: string): string;
/** Remove emoji/pontuação decorativa do início do título das notícias. */
declare function limparTitulo(s: string): string;
declare function fmtData(iso: string | null | undefined): string;
declare function limparCronicaHtml(html: string): string;
export interface DadosEdicao {
    edicao: {
        id: string;
        numero: number;
        assunto: string | null;
        data_envio_prevista: string | null;
        bloco_consultoria?: BlocoConsultoria | null;
        wordpress_post_url?: string | null;
    };
    cronica: {
        titulo: string | null;
        conteudo_html: string | null;
        conteudo: string | null;
        leituras_recomendadas: string | null;
    } | null;
    episodio: {
        titulo: string;
        codigo: string | null;
        url: string | null;
    } | null;
    noticias: Array<{
        id: string;
        titulo: string;
        descricao: string | null;
        url: string | null;
        categoria: string;
        destaque: boolean;
        destino: string;
        ordem: number;
        origem?: string | null;
    }>;
    seccoes: Array<{
        id: string;
        tipo: string;
        ordem: number;
        activo: boolean;
        titulo: string | null;
        texto: string | null;
        texto_botao: string | null;
        url_botao: string | null;
        cor: string | null;
    }>;
    ferramentas: Array<{
        posicao: number;
        nome: string | null;
        descricao: string | null;
        url: string | null;
        emoji: string | null;
        cor: string | null;
    }>;
    /** Total de notícias aprovadas na edição (independente do destino email/site). */
    totalAprovadas: number;
}
export interface CarregarOpts {
    incluirDestinoSite?: boolean;
}
export type BlocoConsultoria = {
    titulo: string;
    subtitulo: string;
    texto_botao: string;
    url_botao: string;
};
export declare function normalizarConsultoria(v: unknown): BlocoConsultoria;
export declare function carregarDadosEdicao(edicaoId: string, opts?: CarregarOpts): Promise<DadosEdicao>;
declare function kicker(icone: string, texto: string, opts?: {
    cor?: string;
    subtitulo?: string;
}): string;
declare function cartaoBranco(inner: string, padding?: string, radius?: number, marginBottom?: number): string;
declare function circulo56(emoji: string, fundo: string, marginBottom?: number): string;
declare function cabecalhoCategoria(g: {
    nome: string;
    emoji: string;
    accent: string;
}): string;
declare function blocoHeader(edicao: DadosEdicao["edicao"]): string;
declare function blocoDestaques(destaques: DadosEdicao["noticias"]): string;
declare function blocoContadores(total: number, naNews: number, url: string): string;
declare function blocoCronica(cronica: DadosEdicao["cronica"]): string;
declare function blocoPodcast(ep: DadosEdicao["episodio"]): string;
declare function blocoFerramentasSemana(fs: DadosEdicao["ferramentas"]): string;
declare function blocoLivro(): string;
declare function blocoConsultoria(c: BlocoConsultoria): string;
declare function blocoRecursos(): string;
declare function blocoPersonalizada(s: DadosEdicao["seccoes"][number]): string;
/**
 * Texto de pré-visualização (preheader) mostrado pelo cliente de email a seguir
 * ao assunto. Resume o conteúdo real da edição — sinal positivo anti-spam e
 * melhor taxa de abertura.
 */
export declare function construirPreheader(d: DadosEdicao): string;
export declare function montarHtml(d: DadosEdicao): string;
export declare function gerarHtmlNewsletter(edicaoId: string): Promise<{
    html: string;
    dados: DadosEdicao;
}>;
export { BG_PAGINA, BG_CARTAO, INK, INK_MED, INK_SEC, TENUE, TENUE_2, DIVISOR, PRIMARIA, SOMBRA, MEDALHAO_GRADIENTES, AVATAR_URL, esc, limparTitulo, fmtData, limparCronicaHtml, kicker, cartaoBranco, circulo56, cabecalhoCategoria, blocoHeader, blocoDestaques, blocoContadores, blocoCronica, blocoPodcast, blocoConsultoria, blocoLivro, blocoRecursos, blocoFerramentasSemana, blocoPersonalizada, };
