// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const CATEGORIA_MAP: Record<string, string>;
export declare function mapCategoria(raw: unknown): string;
export declare function limparLinhasWhatsApp(texto: string): string;
export declare const RE_CABECALHO_WHATSAPP: RegExp;
/**
 * Se o texto tiver ≥ 1 cabeçalho WhatsApp, devolve uma mensagem por corte,
 * com o cabeçalho removido e quebras internas preservadas. Além disso,
 * dentro de cada mensagem, quebra em separadores rígidos (=== / --- / ___).
 * Caso contrário, devolve null — o chamador mantém o fluxo genérico.
 */
export declare function segmentarMensagensWhatsApp(texto: string): string[] | null;
/**
 * Remove o cartão de pré-visualização de link que o WhatsApp cola antes do
 * corpo da mensagem. O cartão termina numa linha com o domínio nu
 * (`www.404media.co`); só o removemos se o corpo seguinte tiver um URL do
 * mesmo domínio e ainda sobrar texto suficiente.
 */
export declare function removerCartaoPreview(mensagem: string): string;
/**
 * Segmenta texto copiado da interface do WhatsApp. Devolve uma mensagem por
 * remetente detectado, sem cabeçalhos, sem preâmbulo de ecrã, sem hora final
 * e sem cartão de pré-visualização. Devolve null quando o formato não é
 * reconhecido (menos de 2 marcadores), para não afectar colagens normais.
 */
export declare function segmentarWhatsAppCopiado(texto: string): string[] | null;
export declare const PARAMS_TRACKING: Set<string>;
export declare function normalizarUrl(url: string): string;
export declare function desembrulharUrl(url: string): string;
/**
 * Devolve o subconjunto de `items` cujo URL (após normalização) ainda não apareceu.
 * O `Set` opcional `jaVistos` é modificado em-place para partilhar estado entre chamadas
 * (ex.: URLs já existentes na BD + URLs repetidos entre feeds).
 */
export declare function dedupPorUrl<T>(items: T[], getUrl: (item: T) => string | null | undefined, jaVistos?: Set<string>): T[];
/**
 * Converte HTML de newsletter em texto estruturado para o extractor.
 * - Descarta <style>, <script>, comentários e pixels de rastreio (1x1).
 * - Preserva parágrafos, títulos e listas.
 * - Colapsa <a> para «texto (url)».
 * - Remove blocos com padrões de rodapé (unsubscribe, view in browser, etc.).
 */
export declare function limparHtmlNewsletter(html: string): string;
/**
 * Extrai "Nome" e "email@dominio" de um cabeçalho From típico.
 * Aceita `Nome <email>`, `"Nome" <email>`, ou só `email`.
 */
export declare function parseFrom(from: string | undefined | null): {
    nome: string | null;
    email: string | null;
};
