// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type VersaoTemplate = "classic" | "revista";
export declare function lerVersaoTemplate(edicaoId: string): Promise<VersaoTemplate>;
/** HTML + texto simples da edição, no formato correspondente à sua versão. */
export declare function renderEdicaoEmail(edicaoId: string): Promise<{
    versao: VersaoTemplate;
    html: string;
    plainText: string;
    problemas: string[];
}>;
