// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
/**
 * Nome interno da campanha na E-goi: edição + lista + título da newsletter.
 * O assunto é truncado para o nome continuar legível na listagem da E-goi.
 */
export declare function nomeInternoCampanha(numero: number, nomeLista: string, assunto?: string | null): string;
export interface ListaAlvo {
    id: string;
    nome: string;
    egoi_lista_id: string;
    tipo: "teste" | "real";
}
export interface ResultadoSync {
    lista_id: string;
    lista_nome: string;
    campaign_hash?: string;
    actualizado_em?: string;
    criado_agora?: boolean;
    ok: boolean;
    erro?: string;
}
export interface SincResultado {
    resultados: ResultadoSync[];
    edicao: {
        id: string;
        numero: number;
        assunto: string;
    };
    html: string;
}
/** Resolve listas por UUIDs e valida activas. */
export declare function resolverListas(admin: SupabaseClient, listaIds: string[]): Promise<{
    ok: true;
    modo: "teste" | "real";
    listas: ListaAlvo[];
} | {
    ok: false;
    mensagem: string;
}>;
export declare function lerConfig(admin: SupabaseClient): Promise<Record<string, string>>;
/** Sincroniza uma única lista (para uso pelo disparador sequencial). Devolve resultado + html + edição. */
export declare function sincronizarUmaLista(admin: SupabaseClient, opts: {
    edicaoId: string;
    lista: ListaAlvo;
    apiKey: string;
    senderId: string;
    quem: string;
    permitirEnviada?: boolean;
}): Promise<{
    ok: true;
    resultado: ResultadoSync;
    html: string;
    edicao: {
        id: string;
        numero: number;
        assunto: string;
    };
} | {
    ok: false;
    status: number;
    mensagem: string;
}>;
/**
 * Sincroniza rascunho na E-goi para cada lista. Reutiliza campanha via PATCH
 * quando já existe linha em egoi_campanhas.
 */
export declare function sincronizar(admin: SupabaseClient, opts: {
    edicaoId: string;
    listas: ListaAlvo[];
    apiKey: string;
    senderId: string;
    quem: string;
}): Promise<{
    ok: true;
    sinc: SincResultado;
} | {
    ok: false;
    status: number;
    mensagem: string;
}>;
export interface Utilizador {
    id: string;
    nome: string;
    papel: "admin" | "curador";
}
export declare function autorizar(SUPABASE_URL: string, ANON_KEY: string, SERVICE_KEY: string, req: Request, modo: "teste" | "real"): Promise<{
    ok: true;
    user: Utilizador;
} | {
    ok: false;
    status: number;
    mensagem: string;
}>;
