// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
type Admin = any;
export type ConfigWp = {
    courseId: number;
};
export declare function lerConfigWp(map: Record<string, string>): ConfigWp;
export interface PublicarInput {
    edicaoId: string;
    numero: number;
    assunto: string;
    siteUrl: string;
    user: string;
    password: string;
    config: ConfigWp;
    status?: "draft" | "publish" | "private";
    /** Metadados opcionais (ex.: Rank Math). Nunca contém credenciais. */
    meta?: Record<string, unknown>;
    existingPostId?: number | null;
}
export type PublicarOk = {
    ok: true;
    post_id: number;
    post_url: string;
    status: string;
    actualizada: boolean;
};
export type PublicarErro = {
    ok: false;
    status?: number;
    mensagem: string;
    detalhe?: unknown;
};
export declare function publicarNoWordpress(input: PublicarInput): Promise<PublicarOk | PublicarErro>;
/**
 * Publica ou actualiza a Lição no WordPress, lendo/gravando o `wordpress_post_id`
 * da edição. Devolve um resumo estável usado pelas Edge Functions e pelo editor.
 */
export declare function publicarOuActualizarLicaoEdicao(admin: Admin, opts: {
    edicaoId: string;
    status: "draft" | "publish" | "private";
    meta?: Record<string, unknown>;
    config: ConfigWp;
    siteUrl: string;
    user: string;
    password: string;
    quem?: string | null;
}): Promise<{
    ok: true;
    tentado: true;
    post_id: number;
    post_url: string;
    status: string;
    actualizada: boolean;
} | {
    ok: false;
    tentado: true;
    mensagem: string;
    post_url: string | null;
}>;
export {};
