// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import { type Carrossel, type FonteCronica } from "./carrossel.ts";
export declare const TIPO = "carrossel_cronica";
export declare function admin(): SupabaseClient;
/** Ensures one content row for the given source. Never touches an existing row. */
export declare function garantirConteudo(sb: SupabaseClient, fonte: FonteCronica): Promise<{
    id: string;
    fonte_aceite_em: string | null;
}>;
/**
 * Enqueue (idempotent). Repeated calls for the same campaign/edition/source do nothing.
 * Never throws: a failure here must not change the newsletter send result.
 */
export declare function enfileirarCarrossel(edicaoId: string, origem: "envio" | "reconciliacao" | "manual"): Promise<{
    ok: boolean;
    jobId?: string;
    motivo?: string;
}>;
/** Calls DeepSeek, logs cost (also for invalid answers) and returns a validated carousel. */
export declare function gerarProposta(sb: SupabaseClient, fonte: FonteCronica): Promise<Carrossel>;
/** Bounded processor (max 5 jobs per run, atomic lease). Safe to call repeatedly. */
export declare function processarJobs(limite?: number): Promise<{
    processados: number;
}>;
/** Recovers eligible sent editions whose job was never enqueued (bounded). */
export declare function reconciliarEdicoesSemJob(limite?: number): Promise<{
    enfileiradas: number;
}>;
