// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import { problemasPorLista, type ListaGate } from "./nl-egoi-tokens-gate-core.ts";
export { problemasPorLista, type ListaGate };
export declare function problemasTokensEnvio(sb: SupabaseClient, apiKey: string, listas: ListaGate[]): Promise<string[]>;
