// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type ListaComCampo } from "./nl-publico-config.ts";
import { type ArmazemProgresso, type ClienteEgoi } from "./nl-egoi-tokens.ts";
export type ListaGate = ListaComCampo & {
    egoi_lista_id: string;
    nome: string;
};
/** Pure core: per-list resolution + readiness with injected E-goi client and store. */
export declare function problemasPorLista(deps: {
    egoi: ClienteEgoi;
    armazem: ArmazemProgresso;
}, listas: ListaGate[], fp: string): Promise<string[]>;
