// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import type { ArmazemProgresso } from "./nl-egoi-tokens.ts";
export declare function armazemSupabase(sb: SupabaseClient): ArmazemProgresso;
