// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export declare const PLACEHOLDER_BASE = "https://endereco-publico-por-configurar.invalid";
/** Base of the public site (edições, briefs, subscrição), without trailing slash. Empty when not configured. */
export declare function basePublica(): string;
/** Same as basePublica() but throws when it is not configured (use on send/publish paths). */
export declare function basePublicaObrigatoria(): string;
/** Base for links inside rendered content: real base, or an explicit .invalid placeholder for previews. */
export declare function baseParaLinks(): string;
/** Edge functions base (public endpoints of this project). */
export declare function baseFuncoes(): string;
/**
 * E-goi merge tag that holds each contact's signed subscription token (e.g. "{!extra_3}").
 * Subscription links never carry the e-mail alone; without this tag configured, sending is blocked.
 */
export declare function tagTokenEgoi(): string;
/** Footer link to the subscription page, authenticated only by the signed token merge tag. */
export declare function linkSubscricao(accao?: "cancelar"): string;
/** RFC 8058 one-click endpoint (List-Unsubscribe), token only. */
export declare function linkUmClique(): string;
export declare function avatarUrl(): string;
/** Blocks sending when public links would be broken or unauthenticated. */
export declare function verificarLigacoesPublicas(): string[];
