// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
type BriefPublico = any; // eslint-disable-line @typescript-eslint/no-explicit-any


export type { BriefPublico };

export interface RespostaBriefPublico {
  brief: BriefPublico | null;
  activos: boolean;
}
export const obterBriefPublicoFn = nlServerFn("brief-publico:obterBriefPublicoFn");
export const previsualizarBriefFn = nlServerFn("brief-publico:previsualizarBriefFn");

