// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
import type { BriefDaEdicao, TipoBrief } from "./newsletter-engine/revista/brief/tipos";


/* ─────────── motor editorial (Fase 2B) ─────────── */

const COMPONENTES = ["tudo", "em_30_segundos", "porque_interessa", "leitura_sugerida"] as const;
const INTENCOES = [
  "normal",
  "mais_pragmatico",
  "mais_curto",
  "menos_opinativo",
  "outro_angulo",
  "simplificar",
] as const;

export type { BriefDaEdicao, TipoBrief };

export interface EdicaoParaBriefs {
  id: string;
  numero: number;
  estado: string;
  assunto: string | null;
}

export interface NoticiaParaBrief {
  id: string;
  titulo: string;
  url: string | null;
  categoria: string;
}
export const listarEdicoesBriefFn = nlServerFn("brief:listarEdicoesBriefFn");
export const listarNoticiasParaBriefFn = nlServerFn("brief:listarNoticiasParaBriefFn");
export const listarBriefsDaEdicaoFn = nlServerFn("brief:listarBriefsDaEdicaoFn");
export const criarBriefFn = nlServerFn("brief:criarBriefFn");
export const removerBriefDaEdicaoFn = nlServerFn("brief:removerBriefDaEdicaoFn");
export const guardarConteudoBriefFn = nlServerFn("brief:guardarConteudoBriefFn");
export const aprovarLeituraBriefFn = nlServerFn("brief:aprovarLeituraBriefFn");
export const revogarLeituraBriefFn = nlServerFn("brief:revogarLeituraBriefFn");

export type ComponenteBriefUi = (typeof COMPONENTES)[number];
export type IntencaoBriefUi = (typeof INTENCOES)[number];

export interface ResultadoGeracaoUi {
  estado: string;
  bloqueado: boolean;
  motivos: string[];
  erro: string | null;
}
export const gerarBriefFn = nlServerFn("brief:gerarBriefFn");
export const reformularBriefFn = nlServerFn("brief:reformularBriefFn");
export const reverificarBriefFn = nlServerFn("brief:reverificarBriefFn");

/* ─────────── workflow editorial na edição (Fase 2C) ─────────── */

export interface EstadoBriefEdicao {
  briefId: string;
  noticiaId: string | null;
  papel: TipoBrief;
  estado: string;
  rotulo: string;
  aprovada: boolean;
  titulo: string;
  slug: string;
  fonteUrl: string | null;
  fontePublisher: string | null;
  em30: string[];
  porqueInteressa: Array<{ rotulo: string; texto: string }>;
  leitura: string;
  pullQuote: string;
  motivos: string[];
  precisaAtencao: boolean;
  erro: string | null;
  actualizadoEm: string;
}
export const estadoBriefsDaEdicaoFn = nlServerFn("brief:estadoBriefsDaEdicaoFn");
export const sincronizarBriefPapelFn = nlServerFn("brief:sincronizarBriefPapelFn");
export const guardarLeituraBriefFn = nlServerFn("brief:guardarLeituraBriefFn");
export const sincronizarBriefsDaEdicaoFn = nlServerFn("brief:sincronizarBriefsDaEdicaoFn");
export const guardarIdentidadeBriefFn = nlServerFn("brief:guardarIdentidadeBriefFn");

