// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
import type { BriefDaEdicao, TipoBrief } from "./newsletter-engine/revista/brief/tipos";


/* ─────────── motor editorial (Fase 2B) ─────────── */

const COMPONENTES = ["tudo", "em_30_segundos", "porque_interessa", "leitura_sugerida"] as const;
const INTENCOES = [
  "normal",
  "mais_pragmatico",
  "mais_curto",
  "menos_opinativo",
  "outro_angulo",
  "simplificar",
] as const;

export type { BriefDaEdicao, TipoBrief };

export interface EdicaoParaBriefs {
  id: string;
  numero: number;
  estado: string;
  assunto: string | null;
}

export interface NoticiaParaBrief {
  id: string;
  titulo: string;
  url: string | null;
  categoria: string;
}
export const listarEdicoesBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").listarEdicoesBriefFn>("brief:listarEdicoesBriefFn");
export const listarNoticiasParaBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").listarNoticiasParaBriefFn>("brief:listarNoticiasParaBriefFn");
export const listarBriefsDaEdicaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").listarBriefsDaEdicaoFn>("brief:listarBriefsDaEdicaoFn");
export const criarBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").criarBriefFn>("brief:criarBriefFn");
export const removerBriefDaEdicaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").removerBriefDaEdicaoFn>("brief:removerBriefDaEdicaoFn");
export const guardarConteudoBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").guardarConteudoBriefFn>("brief:guardarConteudoBriefFn");
export const aprovarLeituraBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").aprovarLeituraBriefFn>("brief:aprovarLeituraBriefFn");
export const revogarLeituraBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").revogarLeituraBriefFn>("brief:revogarLeituraBriefFn");

export type ComponenteBriefUi = (typeof COMPONENTES)[number];
export type IntencaoBriefUi = (typeof INTENCOES)[number];

export interface ResultadoGeracaoUi {
  estado: string;
  bloqueado: boolean;
  motivos: string[];
  erro: string | null;
}
export const gerarBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").gerarBriefFn>("brief:gerarBriefFn");
export const reformularBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").reformularBriefFn>("brief:reformularBriefFn");
export const reverificarBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").reverificarBriefFn>("brief:reverificarBriefFn");

/* ─────────── workflow editorial na edição (Fase 2C) ─────────── */

export interface EstadoBriefEdicao {
  briefId: string;
  noticiaId: string | null;
  papel: TipoBrief;
  estado: string;
  rotulo: string;
  aprovada: boolean;
  titulo: string;
  slug: string;
  fonteUrl: string | null;
  fontePublisher: string | null;
  em30: string[];
  porqueInteressa: Array<{ rotulo: string; texto: string }>;
  leitura: string;
  pullQuote: string;
  motivos: string[];
  precisaAtencao: boolean;
  erro: string | null;
  actualizadoEm: string;
}
export const estadoBriefsDaEdicaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").estadoBriefsDaEdicaoFn>("brief:estadoBriefsDaEdicaoFn");
export const sincronizarBriefPapelFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").sincronizarBriefPapelFn>("brief:sincronizarBriefPapelFn");
export const guardarLeituraBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").guardarLeituraBriefFn>("brief:guardarLeituraBriefFn");
export const sincronizarBriefsDaEdicaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").sincronizarBriefsDaEdicaoFn>("brief:sincronizarBriefsDaEdicaoFn");
export const guardarIdentidadeBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief.functions").guardarIdentidadeBriefFn>("brief:guardarIdentidadeBriefFn");

