// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Server functions públicas do Digital Sprint Brief.
//
// Sem autenticação por desenho — são páginas públicas. Em contrapartida só
// devolvem Briefs aprovados de edições com página web publicada, e respeitam
// o interruptor `briefs_activos`. Não existe qualquer atalho por parâmetro de
// endereço: a pré-visualização interna vive em rotas autenticadas.

import { createServerFn } from "@tanstack/react-start";

export type { BriefPublico };

export interface RespostaBriefPublico {
  brief: BriefPublico | null;
  activos: boolean;
}

export const obterBriefPublicoFn = nlServerFn("brief-publico:obterBriefPublicoFn");
export const previsualizarBriefFn = nlServerFn("brief-publico:previsualizarBriefFn");
