// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



const EVENTOS = [
  // «abertura a partir do email»: pode incluir pré-carregamentos e varrimentos
  // de segurança dos servidores de correio, por isso é sempre um limite
  // superior. A referência para cliques de email continua a ser a E-goi.
  "brief_open_from_email",
  "edition_brief_click",
  "brief_source_click",
  "brief_related_click",
  "brief_commercial_cta",
] as const;

export type EventoBrief = (typeof EVENTOS)[number];

interface EntradaEvento {
  evento: string;
  slug: string;
  edicaoNumero?: number | null;
}
export const registarEventoBriefFn = nlServerFn("brief-analytics:registarEventoBriefFn");

