// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
type BriefPublico = any; // eslint-disable-line @typescript-eslint/no-explicit-any


export type { BriefPublico };

export interface RespostaBriefPublico {
  brief: BriefPublico | null;
  activos: boolean;
}
export const obterBriefPublicoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief-publico.functions").obterBriefPublicoFn>("brief-publico:obterBriefPublicoFn");
export const previsualizarBriefFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/brief-publico.functions").previsualizarBriefFn>("brief-publico:previsualizarBriefFn");

