// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export type EventoBrief = (typeof EVENTOS)[number];
export const registarEventoBriefFn = nlServerFn("brief-analytics:registarEventoBriefFn");
