// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Server functions para gerir o motor de Curadoria de Ferramentas:
// - Correr recolha manual (usa a mesma rota pública que o cron)
// - CRUD das fontes de directório (Toolify/Futurepedia/TAAFT)
// - Configuração semanal (dia_semana, hora, tecto, activo)

import { createServerFn } from "@tanstack/react-start";

export type FonteDirectorio = {
  id: string;
  nome: string;
  url_listagem: string | null;
  url_feed: string;
  activa: boolean;
  ultima_recolha: string | null;
  criada_em: string;
};

export type CuradoriaFerramentasConfig = {
  dia_semana: number; // 0-6 (0=Domingo)
  hora: number;       // 0-23
  max_por_corrida: number;
  activo: boolean;
  actualizado_em: string;
};

export type ResumoCorridaFerramentas = {
  ok: boolean;
  inseridas: number;
  descartadas_por_ia: number;
  candidatos: number;
  fontes: number;
  custo_usd: number;
  mensagem?: string;
};
export const correrCuradoriaFerramentasAgora = nlServerFn("curadoria-ferramentas:correrCuradoriaFerramentasAgora");
export const listarFontesDirectorios = nlServerFn("curadoria-ferramentas:listarFontesDirectorios");
export const criarFonteDirectorio = nlServerFn("curadoria-ferramentas:criarFonteDirectorio");
