// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



export type FonteDirectorio = {
  id: string;
  nome: string;
  url_listagem: string | null;
  url_feed: string;
  activa: boolean;
  ultima_recolha: string | null;
  criada_em: string;
};

export type CuradoriaFerramentasConfig = {
  dia_semana: number; // 0-6 (0=Domingo)
  hora: number;       // 0-23
  max_por_corrida: number;
  activo: boolean;
  actualizado_em: string;
};

export type ResumoCorridaFerramentas = {
  ok: boolean;
  inseridas: number;
  descartadas_por_ia: number;
  candidatos: number;
  fontes: number;
  custo_usd: number;
  mensagem?: string;
};
export const correrCuradoriaFerramentasAgora = nlServerFn("curadoria-ferramentas:correrCuradoriaFerramentasAgora");
export const listarFontesDirectorios = nlServerFn("curadoria-ferramentas:listarFontesDirectorios");
export const criarFonteDirectorio = nlServerFn("curadoria-ferramentas:criarFonteDirectorio");
export const actualizarFonteDirectorio = nlServerFn("curadoria-ferramentas:actualizarFonteDirectorio");
export const apagarFonteDirectorio = nlServerFn("curadoria-ferramentas:apagarFonteDirectorio");
export const getConfigCuradoriaFerramentas = nlServerFn("curadoria-ferramentas:getConfigCuradoriaFerramentas");
export const setConfigCuradoriaFerramentas = nlServerFn("curadoria-ferramentas:setConfigCuradoriaFerramentas");
export const alternarDirectoriosEmLote = nlServerFn("curadoria-ferramentas:alternarDirectoriosEmLote");

