// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export const descobrirFeed = nlServerFn("curadoria:descobrirFeed");
export const testarFeed = nlServerFn("curadoria:testarFeed");
export const correrCuradoriaAgora = nlServerFn("curadoria:correrCuradoriaAgora");
export const correrFonteAgora = nlServerFn("curadoria:correrFonteAgora");
export const alternarFontesEmLote = nlServerFn("curadoria:alternarFontesEmLote");
