// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";


const UA_DESCOBERTA = "DigitalSprintBot/1.0 (+descoberta)";
const CAMINHOS_COMUNS_FEED = [
  "/feed", "/feed/", "/rss", "/rss/", "/rss.xml", "/feed.xml",
  "/atom.xml", "/index.xml", "/?feed=rss2", "/blog/feed", "/news/feed",
];
export const descobrirFeed = nlServerFn("curadoria:descobrirFeed");
