// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



export type EstadoSecrets = {
  deepseek: boolean;
  egoi: boolean;
  wp_url: boolean;
  wp_user: boolean;
  wp_pass: boolean;
};
export const verificarSecretsAPI = nlServerFn("definicoes:verificarSecretsAPI");
export const getWebhookCloudMailinUrl = nlServerFn("definicoes:getWebhookCloudMailinUrl");

