// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



export type EstadoSecrets = {
  deepseek: boolean;
  egoi: boolean;
  wp_url: boolean;
  wp_user: boolean;
  wp_pass: boolean;
};
export const verificarSecretsAPI = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/definicoes.functions").verificarSecretsAPI>("definicoes:verificarSecretsAPI");
export const getWebhookCloudMailinUrl = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/definicoes.functions").getWebhookCloudMailinUrl>("definicoes:getWebhookCloudMailinUrl");

