// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";


export const corrigirDescricoes = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/descricoes.functions").corrigirDescricoes>("descricoes:corrigirDescricoes");

