// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Server functions dos destinos de publicação da Revista.
//
// O cliente pede acções e lê estados; toda a orquestração (e qualquer
// credencial futura) vive no servidor.
import { createServerFn } from "@tanstack/react-start";

export type { DestinosEdicao };
export const estadoDestinosFn = nlServerFn("destinos:estadoDestinosFn");
export const guardarUrlCronicaFn = nlServerFn("destinos:guardarUrlCronicaFn");
export const repetirDestinoFn = nlServerFn("destinos:repetirDestinoFn");
export const previewArtigoCronicaFn = nlServerFn("destinos:previewArtigoCronicaFn");
export const estadoIntegracaoCronicaFn = nlServerFn("destinos:estadoIntegracaoCronicaFn");
export const diagnosticoCronicaFn = nlServerFn("destinos:diagnosticoCronicaFn");
export const publicarCronicaFn = nlServerFn("destinos:publicarCronicaFn");
export const publicarArtigoCronicaFn = nlServerFn("destinos:publicarArtigoCronicaFn");
export const actualizarArtigoCronicaFn = nlServerFn("destinos:actualizarArtigoCronicaFn");
export const reconciliarHashCronicaFn = nlServerFn("destinos:reconciliarHashCronicaFn");
export const contarArtigosPorSlugFn = nlServerFn("destinos:contarArtigosPorSlugFn");
export const prontidaoRevistaFn = nlServerFn("destinos:prontidaoRevistaFn");
