// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
type DestinosEdicao = any; // eslint-disable-line @typescript-eslint/no-explicit-any


export type { DestinosEdicao };
export const estadoDestinosFn = nlServerFn("destinos:estadoDestinosFn");
export const guardarUrlCronicaFn = nlServerFn("destinos:guardarUrlCronicaFn");
export const repetirDestinoFn = nlServerFn("destinos:repetirDestinoFn");
export const previewArtigoCronicaFn = nlServerFn("destinos:previewArtigoCronicaFn");
export const estadoIntegracaoCronicaFn = nlServerFn("destinos:estadoIntegracaoCronicaFn");
export const diagnosticoCronicaFn = nlServerFn("destinos:diagnosticoCronicaFn");
export const publicarCronicaFn = nlServerFn("destinos:publicarCronicaFn");
export const publicarArtigoCronicaFn = nlServerFn("destinos:publicarArtigoCronicaFn");
export const actualizarArtigoCronicaFn = nlServerFn("destinos:actualizarArtigoCronicaFn");
export const reconciliarHashCronicaFn = nlServerFn("destinos:reconciliarHashCronicaFn");
export const contarArtigosPorSlugFn = nlServerFn("destinos:contarArtigosPorSlugFn");
export const prontidaoRevistaFn = nlServerFn("destinos:prontidaoRevistaFn");

