// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



interface EncurtarInput {
  titulo: string;
  descricao: string;
  alvo?: number; // caracteres alvo, default 160
}
export const encurtarDescricao = nlServerFn("encurtar-descricao:encurtarDescricao");

