// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Encurta a descrição de uma notícia para caber em 2–3 linhas nos cartões
// da newsletter, reescrevendo em pt-PT sem `…`. Usado à peça pelo botão
// "✂️ Encurtar com IA" e em massa pela acção "Ajustar descrições".
//
// Fonte de IA: DeepSeek (única IA autorizada no projecto).

import { createServerFn } from "@tanstack/react-start";

interface EncurtarInput {
  titulo: string;
  descricao: string;
  alvo?: number; // caracteres alvo, default 160
}

const PROMPT = `És editor da newsletter Digital Sprint (marketing, tecnologia e IA), em português de Portugal EUROPEU.

Reescreve a descrição de uma notícia para caber em duas linhas dos cartões.

REGRAS OBRIGATÓRIAS:
- Extensão: entre 18 e 30 palavras (contagem por espaços). Nem menos, nem mais.
- pt-PT europeu, tratamento por "tu" quando aplicável (nunca "você").
- Léxico EUROPEU obrigatório: "funcionalidade" (nunca «recurso»), "subscritor" (nunca «assinante»), "utilizador" (nunca «usuário»), "ficheiro" (nunca «arquivo»), "ecrã" (nunca «tela»), "telemóvel" (nunca «celular»), "equipa" (nunca «time» quando se refere a grupo de trabalho).
- Uma ou duas frases COMPLETAS. Nunca uses "..." nem cortes bruscos.
- Preserva o facto essencial (o que aconteceu / o que muda).
- Não repitas palavras-chave já presentes no título.
- Sem emojis, sem CAPS, sem clickbait, sem juízo de valor.
- Nunca comeces com prefixos rotulares tipo "Descrição:", "Resumo:", "Notícia:".
- Devolve APENAS JSON válido: {"descricao": "..."}`;

const PROMPT_ESTENDER = `${PROMPT}

CORRECÇÃO IMPORTANTE: a versão anterior ficou CURTA (< 18 palavras). Reescreve com MAIS DETALHE factual, mantendo entre 18 e 30 palavras, sem inventar nada.`;
export const encurtarDescricao = nlServerFn("encurtar-descricao:encurtarDescricao");
