// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";


export const previewEdicaoFn = nlServerFn("envio:previewEdicaoFn");
export const sincronizarRascunhoFn = nlServerFn("envio:sincronizarRascunhoFn");
export const dispararEgoiFn = nlServerFn("envio:dispararEgoiFn");
export const prepararEnvioFn = nlServerFn("envio:prepararEnvioFn");
export const dispararListaFn = nlServerFn("envio:dispararListaFn");
export const repetirListaFn = nlServerFn("envio:repetirListaFn");
export const reconciliarEdicaoFn = nlServerFn("envio:reconciliarEdicaoFn");
export const finalizarEnvioFn = nlServerFn("envio:finalizarEnvioFn");
export const publicarWordpressFn = nlServerFn("envio:publicarWordpressFn");
export const agendarEnvioFn = nlServerFn("envio:agendarEnvioFn");
export const cancelarAgendamentoFn = nlServerFn("envio:cancelarAgendamentoFn");

