// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export type FerramentaSugerida = {
  id: string;
  nome: string;
  url: string;
  descricao: string | null;
  descricao_original?: string | null;
  emoji?: string | null;
  cor?: string | null;
  categoria: string | null;
  remetente: string | null;
  assunto_origem: string | null;
  fonte_email_id: string | null;
  fonte_directorio_id?: string | null;
  estado: "pendente" | "aprovada" | "rejeitada" | "arquivada";
  aprovada_em: string | null;
  criado_em: string;
  edicao_aprovada_id?: string | null;
  edicao_aprovada_numero?: number | null;
export type FiltroEstadoFerramenta = "pendente" | "aprovada" | "rejeitada" | "arquivada" | "todas";
export const listarFerramentas = nlServerFn("ferramentas:listarFerramentas");
export const actualizarEstadoFerramenta = nlServerFn("ferramentas:actualizarEstadoFerramenta");
export const apagarFerramenta = nlServerFn("ferramentas:apagarFerramenta");
export const listarFerramentasDoEmail = nlServerFn("ferramentas:listarFerramentasDoEmail");
export const aprovarFerramentaParaRascunho = nlServerFn("ferramentas:aprovarFerramentaParaRascunho");
export const listarEdicoesDestinoFerramenta = nlServerFn("ferramentas:listarEdicoesDestinoFerramenta");
export const rejeitarFerramentaComBan = nlServerFn("ferramentas:rejeitarFerramentaComBan");
export const contarFerramentasArquivadas = nlServerFn("ferramentas:contarFerramentasArquivadas");
