// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



export type FerramentaSugerida = {
  id: string;
  nome: string;
  url: string;
  descricao: string | null;
  descricao_original?: string | null;
  emoji?: string | null;
  cor?: string | null;
  categoria: string | null;
  remetente: string | null;
  assunto_origem: string | null;
  fonte_email_id: string | null;
  fonte_directorio_id?: string | null;
  estado: "pendente" | "aprovada" | "rejeitada" | "arquivada";
  aprovada_em: string | null;
  criado_em: string;
  edicao_aprovada_id?: string | null;
  edicao_aprovada_numero?: number | null;
};

export type FiltroEstadoFerramenta = "pendente" | "aprovada" | "rejeitada" | "arquivada" | "todas";
export const listarFerramentas = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").listarFerramentas>("ferramentas:listarFerramentas");
export const actualizarEstadoFerramenta = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").actualizarEstadoFerramenta>("ferramentas:actualizarEstadoFerramenta");
export const apagarFerramenta = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").apagarFerramenta>("ferramentas:apagarFerramenta");
export const listarFerramentasDoEmail = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").listarFerramentasDoEmail>("ferramentas:listarFerramentasDoEmail");
export const aprovarFerramentaParaRascunho = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").aprovarFerramentaParaRascunho>("ferramentas:aprovarFerramentaParaRascunho");
export const listarEdicoesDestinoFerramenta = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").listarEdicoesDestinoFerramenta>("ferramentas:listarEdicoesDestinoFerramenta");
export const rejeitarFerramentaComBan = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").rejeitarFerramentaComBan>("ferramentas:rejeitarFerramentaComBan");
export const contarFerramentasArquivadas = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ferramentas.functions").contarFerramentasArquivadas>("ferramentas:contarFerramentasArquivadas");

