// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";

export const contarFilaCuradoria = nlServerFn("fila-curadoria:contarFilaCuradoria");
export const processarFilaCuradoria = nlServerFn("fila-curadoria:processarFilaCuradoria");
export const retomarFalhadosCuradoria = nlServerFn("fila-curadoria:retomarFalhadosCuradoria");
export const definirModoManualCuradoria = nlServerFn("fila-curadoria:definirModoManualCuradoria");
export const limparFilaAntigaCuradoria = nlServerFn("fila-curadoria:limparFilaAntigaCuradoria");
