// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";


export const contarFilaCuradoria = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/fila-curadoria.functions").contarFilaCuradoria>("fila-curadoria:contarFilaCuradoria");
export const processarFilaCuradoria = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/fila-curadoria.functions").processarFilaCuradoria>("fila-curadoria:processarFilaCuradoria");
export const retomarFalhadosCuradoria = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/fila-curadoria.functions").retomarFalhadosCuradoria>("fila-curadoria:retomarFalhadosCuradoria");
export const definirModoManualCuradoria = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/fila-curadoria.functions").definirModoManualCuradoria>("fila-curadoria:definirModoManualCuradoria");
export const limparFilaAntigaCuradoria = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/fila-curadoria.functions").limparFilaAntigaCuradoria>("fila-curadoria:limparFilaAntigaCuradoria");

