// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



interface LeituraInput {
  titulo: string;
  resumo: string;
  descricao: string;
  categoria: string;
  url: string;
  edicao_id: string | null;
  noticia_id: string | null;
}
export const gerarMinhaLeitura = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/ia-leitura.functions").gerarMinhaLeitura>("ia-leitura:gerarMinhaLeitura");

