// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export const gerarMinhaLeitura = nlServerFn("ia-leitura:gerarMinhaLeitura");
