// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Gera «A minha leitura» de um destaque da edição Revista.
//
// Fonte de IA: DeepSeek (única IA autorizada no projecto). A função devolve
// apenas uma proposta — quem grava é o editor, no cliente.

import { createServerFn } from "@tanstack/react-start";

interface LeituraInput {
  titulo: string;
  resumo: string;
  descricao: string;
  categoria: string;
  url: string;
  edicao_id: string | null;
  noticia_id: string | null;
}

/** Limite de contexto do artigo: chega para interpretar sem inflacionar o custo. */
const MAX_CORPO_LEITURA = 6000;
export const gerarMinhaLeitura = nlServerFn("ia-leitura:gerarMinhaLeitura");
