// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
import type { FotoPexels } from "./pexels-tipos";


export type { FotoPexels } from "./pexels-tipos";
export const pesquisarPexelsFn = nlServerFn("imagens:pesquisarPexelsFn");
export const importarPexelsFn = nlServerFn("imagens:importarPexelsFn");
export const carregarImagemFn = nlServerFn("imagens:carregarImagemFn");
export const obterImagemBase64Fn = nlServerFn("imagens:obterImagemBase64Fn");

