// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Sugestão de linhas de assunto para a próxima edição da newsletter.
// Fonte de IA: DeepSeek (única IA autorizada no projecto).

import { createServerFn } from "@tanstack/react-start";


interface SugerirAssuntoInput {
  edicaoId: string;
  aperfeicoar?: {
    assunto: string;
    preheader: string;
  };
}

export type TecnicaAssunto = "curiosidade" | "dado_concreto" | "cronica";
export interface SugestaoAssunto {
  texto: string;
  preheader: string;
  tecnica: TecnicaAssunto;
  caracteres: number;
}

const MIN_CRONICA_UTIL = 150;

const PROMPT_SISTEMA = `És um copywriter especialista em linhas de assunto de email, a escrever para uma newsletter portuguesa de marketing e tecnologia (Digital Sprint, por Frederico Carvalho, tom directo e conhecedor, nunca hype vazio).

Recebes o conteúdo completo de uma edição (destaques, radar, crónica, podcast, recomendações, ferramentas e blocos comerciais). Gera exactamente 3 pares de assunto e pré-cabeçalho, cada um usando uma técnica DIFERENTE:

1. CURIOSIDADE — cria intriga genuína sobre algo da edição, sem ser clickbait vazio (a promessa tem de ser cumprida pelo conteúdo real).
2. DADO CONCRETO — usa um número, percentagem, valor monetário, data ou nome próprio EXTRAÍDO LITERALMENTE do conteúdo da edição (destaques, crónica, podcast ou ferramentas). PROIBIDO usar meta-referências ao processo (ex: "3 destaques desta semana", "5 ferramentas novas", "N notícias hoje") — o número tem de vir do conteúdo em si, não da estrutura da newsletter.
3. ANCORADO NA CRÓNICA — se a crónica tiver texto substancial, usa o ângulo/tese dela como base; se a crónica estiver vazia, usa o destaque mais surpreendente em vez disso.

Regras para todas as sugestões:
- Português EUROPEU (pt-PT), tom directo, sem exclamações excessivas, sem CAIXA ALTA.
- Entre 40 e 55 caracteres (conta os caracteres exactos).
- Sem emojis, a menos que sirva um propósito claro de destaque visual (máx. 1).
- Nunca usar palavras-gatilho de spam (grátis, urgente, clique aqui, últimas horas).
- PROIBIDO qualquer prefixo rotular no início do texto: "Assunto:", "Crónica:", "Título:", "Dado:", "Curiosidade:", ou qualquer outro padrão "Palavra:" antes do texto real. O campo "texto" contém APENAS a linha de assunto final que o subscritor vê.
- A promessa do assunto tem de corresponder a algo real dentro da edição — nunca prometer o que o conteúdo não cumpre.
- O pré-cabeçalho complementa o assunto sem o repetir, tem entre 55 e 100 caracteres e acrescenta um segundo motivo real para abrir.
- Assunto e pré-cabeçalho devem funcionar como um par coerente.

Devolve APENAS JSON: {"sugestoes":[{ "assunto": "...", "preheader": "...", "tecnica": "curiosidade"|"dado_concreto"|"cronica" }]}`;
export const sugerirAssunto = nlServerFn("newsletter-ia:sugerirAssunto");
