// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export type TecnicaAssunto = "curiosidade" | "dado_concreto" | "cronica";
export interface SugestaoAssunto {
  texto: string;
  preheader: string;
  tecnica: TecnicaAssunto;
  caracteres: number;
export const sugerirAssunto = nlServerFn("newsletter-ia:sugerirAssunto");
