// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";




interface SugerirAssuntoInput {
  edicaoId: string;
  aperfeicoar?: {
    assunto: string;
    preheader: string;
  };
}

export type TecnicaAssunto = "curiosidade" | "dado_concreto" | "cronica";
export interface SugestaoAssunto {
  texto: string;
  preheader: string;
  tecnica: TecnicaAssunto;
  caracteres: number;
}
export const sugerirAssunto = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/newsletter-ia.functions").sugerirAssunto>("newsletter-ia:sugerirAssunto");
export const resumirEpisodioPodcast = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/newsletter-ia.functions").resumirEpisodioPodcast>("newsletter-ia:resumirEpisodioPodcast");

