// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Sugestão editorial: destaques + destino por notícia, para a edição actual.
// IA única autorizada: DeepSeek.

import { createServerFn } from "@tanstack/react-start";

export interface SugestaoOrganizacao {
  id: string;
  titulo: string;
  categoria: string | null;
  destaque_proposto: boolean;
  destino_proposto: "news" | "site";
  justificacao: string;
  // Estado actual (para saber se a sugestão altera algo)
  destaque_actual: boolean;
  destino_actual: "news" | "site";
}

export interface SugerirOrganizacaoResultado {
  ok: boolean;
  motivo?: string;
  aviso?: string;
  sugestoes: SugestaoOrganizacao[];
}

const PROMPT_SISTEMA = `És um editor sénior de uma newsletter portuguesa de marketing e tecnologia (Digital Sprint). Escolhes o que abre a edição e o que fica só no site.

A audiência é portuguesa, sénior, interessada em marketing digital, IA aplicada, comportamento do consumidor e plataformas (Meta, Instagram, TikTok, LinkedIn, YouTube, X).

Regras rígidas de output:
- Escolhes EXACTAMENTE 3 destaques (destaque: true, destino: "news").
- Do resto, apontas ~7-8 para "news" (corpo da newsletter) e o remanescente para "site" (só na página, não no email).
- Total ideal em "news" (destaques + corpo): ~10-11 notícias.
- Nunca inventes IDs — usa apenas os que recebes.
- Justificação em português europeu (pt-PT), máximo 15 palavras, directa, sem hype.
- Devolves APENAS JSON válido, sem markdown, sem prefixos.

Formato: {"sugestoes":[{"id":"uuid","destaque":true|false,"destino":"news"|"site","justificacao":"..."}]}`;

interface Input {
  edicaoId: string;
}

export const sugerirOrganizacaoEdicao = nlServerFn("organizar-edicao:sugerirOrganizacaoEdicao");
