// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



export interface SugestaoOrganizacao {
  id: string;
  titulo: string;
  categoria: string | null;
  destaque_proposto: boolean;
  destino_proposto: "news" | "site";
  justificacao: string;
  // Estado actual (para saber se a sugestão altera algo)
  destaque_actual: boolean;
  destino_actual: "news" | "site";
}

export interface SugerirOrganizacaoResultado {
  ok: boolean;
  motivo?: string;
  aviso?: string;
  sugestoes: SugestaoOrganizacao[];
}

interface Input {
  edicaoId: string;
}
export const sugerirOrganizacaoEdicao = nlServerFn("organizar-edicao:sugerirOrganizacaoEdicao");

