// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export type IdiomaFonte = "pt-PT" | "pt-BR" | "en" | "es" | "fr" | "de" | "outro";
export interface Candidato {
  url: string;
  dominio: string;
  titulo: string;
  snippet: string;
  score: number;
  motivo: string;
  data: string;        // DD/MM/AAAA quando conhecida; vazio caso contrário
  dataISO?: string;    // ISO absoluta apenas quando lida de meta de publicação real
  idioma: IdiomaFonte;
export const pesquisarFonteIA = nlServerFn("pesquisar-fonte:pesquisarFonteIA");
