// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



/**
 * Pesquisa web para encontrar uma fonte alternativa para uma notícia.
 * Combina DuckDuckGo (HTML público) com ranking por Gemini.
 */

interface Input {
  titulo: string;
  descricao?: string | null;
  urlActual?: string | null;
}

export type IdiomaFonte = "pt-PT" | "pt-BR" | "en" | "es" | "fr" | "de" | "outro";

export interface Candidato {
  url: string;
  dominio: string;
  titulo: string;
  snippet: string;
  score: number;
  motivo: string;
  data: string;        // DD/MM/AAAA quando conhecida; vazio caso contrário
  dataISO?: string;    // ISO absoluta apenas quando lida de meta de publicação real
  idioma: IdiomaFonte;
}

type MetaPagina = {
  data?: string;
  dataISO?: string;
  idioma?: IdiomaFonte;
  urlFinal?: string;
  status?: number;
};
export const pesquisarFonteIA = nlServerFn("pesquisar-fonte:pesquisarFonteIA");

