// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



type Papel = "admin" | "curador";
export const extrairNoticias = nlServerFn("processar-noticias:extrairNoticias");
export const confirmarNoticias = nlServerFn("processar-noticias:confirmarNoticias");
export const guardarModeloIA = nlServerFn("processar-noticias:guardarModeloIA");
export const testarModeloIA = nlServerFn("processar-noticias:testarModeloIA");

