// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Funções de servidor que substituem a antiga Edge Function `processar-noticias`.
// Ficheiro fino: só declarações `createServerFn` — a lógica vive em
// `processar-noticias.server.ts`.

import { createServerFn } from "@tanstack/react-start";

type Papel = "admin" | "curador";
export const extrairNoticias = nlServerFn("processar-noticias:extrairNoticias");
export const confirmarNoticias = nlServerFn("processar-noticias:confirmarNoticias");
export const guardarModeloIA = nlServerFn("processar-noticias:guardarModeloIA");
export const testarModeloIA = nlServerFn("processar-noticias:testarModeloIA");
