// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
import { type PropostaPecas } from "@/newsletter/lib/newsletter-engine/revista/pecas-proposta";


export type { PropostaPecas };
export const proporPecasCronicaFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/propor-pecas.functions").proporPecasCronicaFn>("propor-pecas:proporPecasCronicaFn");

