// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export interface PropostaApresentacaoResultado {
  assinatura: string;
  titulo: string;
  subtitulo: string;
  lede: string;
  excerto: string;
  pullQuote: string;
  momento: { etiqueta: string; valor: string; descricao: string };
  momentoRejeitado: boolean;
  imagem: { alt: string; termo: string; escolhida: FotoPexels | null; alternativas: FotoPexels[] };
  avisos: string[];
export const proporApresentacaoFn = nlServerFn("propor-apresentacao:proporApresentacaoFn");
