// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Proposta de «Apresentação Revista» a partir do texto já escrito da crónica.
//
// Padrão proposal-first: a função nunca grava nada — devolve uma proposta que
// o editor revê e aplica campo a campo. Uma única chamada DeepSeek por pedido.

import { createServerFn } from "@tanstack/react-start";
import type { FotoPexels } from "@/lib/pexels-tipos";

export const MIN_CARACTERES_CRONICA = 200;

export interface PropostaApresentacaoResultado {
  assinatura: string;
  titulo: string;
  subtitulo: string;
  lede: string;
  excerto: string;
  pullQuote: string;
  momento: { etiqueta: string; valor: string; descricao: string };
  momentoRejeitado: boolean;
  imagem: { alt: string; termo: string; escolhida: FotoPexels | null; alternativas: FotoPexels[] };
  avisos: string[];
}

export const proporApresentacaoFn = nlServerFn("propor-apresentacao:proporApresentacaoFn");
