// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Proposta das peças móveis da crónica (lede, frase de destaque, momento).
// Proposal-first: não grava nada; o editor revê e aplica.

import { createServerFn } from "@tanstack/react-start";
import { validarPropostaPecas, type PropostaPecas } from "@/lib/newsletter-engine/revista/pecas-proposta";

export type { PropostaPecas };
export const proporPecasCronicaFn = nlServerFn("propor-pecas:proporPecasCronicaFn");
