// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
export type AmbitoRecomeco = (typeof AMBITOS_RECOMECO)[number];
export const recomecarEdicaoFn = nlServerFn("recomecar-edicao:recomecarEdicaoFn");
