// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
import type { Database } from "@/integrations/supabase/types";


type RevistaUpdate = Database["public"]["Tables"]["revista_edicao"]["Update"];

export const AMBITOS_RECOMECO = ["noticias", "cronica", "blocos", "assunto", "briefs"] as const;
export type AmbitoRecomeco = (typeof AMBITOS_RECOMECO)[number];
export const recomecarEdicaoFn = nlServerFn("recomecar-edicao:recomecarEdicaoFn");

