// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Recomeçar uma edição em rascunho: limpa o conteúdo escolhido, mantendo
// número, data e formato. As notícias voltam a pendentes (nada é apagado).
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

type RevistaUpdate = Database["public"]["Tables"]["revista_edicao"]["Update"];

export const AMBITOS_RECOMECO = ["noticias", "cronica", "blocos", "assunto", "briefs"] as const;
export type AmbitoRecomeco = (typeof AMBITOS_RECOMECO)[number];

const schema = z.object({
  edicaoId: z.string().uuid(),
  ambitos: z.array(z.enum(AMBITOS_RECOMECO)).min(1),
  confirmacao: z.string(),
  quem: z.string().max(200),
});
export const recomecarEdicaoFn = nlServerFn("recomecar-edicao:recomecarEdicaoFn");
