// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Pré-visualização interna da versão web Revista.
// Autenticada por desenho: mostra edições ainda não publicadas, pelo que
// nunca pode ser exposta em rotas públicas. A regra pública de publicação
// mantém-se intacta em `publicacao.server.ts`.

import { createServerFn } from "@tanstack/react-start";
export const previsualizarEdicaoWebFn = nlServerFn("revista-preview:previsualizarEdicaoWebFn");
