// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
// Server functions públicas da edição web Revista.
//
// Sem autenticação por desenho: são páginas públicas. Em contrapartida, só
// devolvem conteúdo de edições já publicadas (ver `publicacao.server.ts`).

import { createServerFn } from "@tanstack/react-start";

export type { PaginaEdicaoPublica, ResumoEdicaoPublica, GrupoAtualidades, VizinhaPublica };
export const baseUrlEdicoesFn = nlServerFn("revista-web:baseUrlEdicoesFn");
export const listarEdicoesPublicasFn = nlServerFn("revista-web:listarEdicoesPublicasFn");
export const obterEdicaoPublicaFn = nlServerFn("revista-web:obterEdicaoPublicaFn");
