// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
type PaginaEdicaoPublica = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type ResumoEdicaoPublica = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type GrupoAtualidades = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type VizinhaPublica = any; // eslint-disable-line @typescript-eslint/no-explicit-any


export type { PaginaEdicaoPublica, ResumoEdicaoPublica, GrupoAtualidades, VizinhaPublica };
export const baseUrlEdicoesFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/revista-web.functions").baseUrlEdicoesFn>("revista-web:baseUrlEdicoesFn");
export const listarEdicoesPublicasFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/revista-web.functions").listarEdicoesPublicasFn>("revista-web:listarEdicoesPublicasFn");
export const obterEdicaoPublicaFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/revista-web.functions").obterEdicaoPublicaFn>("revista-web:obterEdicaoPublicaFn");

