// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



/**
 * Endpoints públicos da página de gestão de subscrição.
 * Não exigem sessão — quem chega aqui vem do rodapé de um email.
 * Nunca devolvem dados de terceiros: só o estado do email indicado.
 */

export interface EstadoPublico {
  ok: boolean;
  email: string | null;
  estado: "activa" | "cancelada" | "pausada" | "mensal";
  retomaEm: string | null;
  mensagem?: string;
}
export const estadoSubscricaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/subscricao.functions").estadoSubscricaoFn>("subscricao:estadoSubscricaoFn");
export const aplicarAccaoSubscricaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/subscricao.functions").aplicarAccaoSubscricaoFn>("subscricao:aplicarAccaoSubscricaoFn");
export const resumoSubscricoesFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/subscricao.functions").resumoSubscricoesFn>("subscricao:resumoSubscricoesFn");
export const testarSubscricaoFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/subscricao.functions").testarSubscricaoFn>("subscricao:testarSubscricaoFn");
export const urlWebhookEgoiFn = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/subscricao.functions").urlWebhookEgoiFn>("subscricao:urlWebhookEgoiFn");

