// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";


/**
 * Endpoints públicos da página de gestão de subscrição.
 * Não exigem sessão — quem chega aqui vem do rodapé de um email.
 * Nunca devolvem dados de terceiros: só o estado do email indicado.
 */

export interface EstadoPublico {
  ok: boolean;
  email: string | null;
  estado: "activa" | "cancelada" | "pausada" | "mensal";
  retomaEm: string | null;
  mensagem?: string;
}

export const estadoSubscricaoFn = nlServerFn("subscricao:estadoSubscricaoFn");
export const aplicarAccaoSubscricaoFn = nlServerFn("subscricao:aplicarAccaoSubscricaoFn");
export const resumoSubscricoesFn = nlServerFn("subscricao:resumoSubscricoesFn");
export const testarSubscricaoFn = nlServerFn("subscricao:testarSubscricaoFn");
export const urlWebhookEgoiFn = nlServerFn("subscricao:urlWebhookEgoiFn");
