// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";
type ItemLink = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type ContextoLink = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type EstadoLink = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type ResumoLinks = any; // eslint-disable-line @typescript-eslint/no-explicit-any
type ResultadoVerificarLinks = any; // eslint-disable-line @typescript-eslint/no-explicit-any


export type { ItemLink, ContextoLink, EstadoLink, ResumoLinks, ResultadoVerificarLinks };
export const verificarLinksEdicao = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/verificar-links.functions").verificarLinksEdicao>("verificar-links:verificarLinksEdicao");

/* ─── Verificação de um único URL (para o UrlEditor) ─── */

export interface ResultadoUmLink {
  url: string;
  estado: EstadoLink;
  status: number;
  redirect_para?: string;
}
export const verificarUmLink = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/verificar-links.functions").verificarUmLink>("verificar-links:verificarUmLink");
export const ignorarLink = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/verificar-links.functions").ignorarLink>("verificar-links:ignorarLink");
export const reactivarLink = nlServerFn<typeof import("@/newsletter/_tipos-servidor/nl-app/lib/verificar-links.functions").reactivarLink>("verificar-links:reactivarLink");

