// GENERATED by scripts/port-newsletter.py — RPC stubs; real handlers run in nl-api.
import { nlServerFn } from "@/newsletter/shim/start";



export type { ItemLink, ContextoLink, EstadoLink, ResumoLinks, ResultadoVerificarLinks };
export const verificarLinksEdicao = nlServerFn("verificar-links:verificarLinksEdicao");

/* ─── Verificação de um único URL (para o UrlEditor) ─── */

export interface ResultadoUmLink {
  url: string;
  estado: EstadoLink;
  status: number;
  redirect_para?: string;
}
export const verificarUmLink = nlServerFn("verificar-links:verificarUmLink");
export const ignorarLink = nlServerFn("verificar-links:ignorarLink");
export const reactivarLink = nlServerFn("verificar-links:reactivarLink");

