// GENERATED by scripts/port-newsletter.py — registry of server functions.
import * as m0 from "./lib/brief-analytics.functions.ts";
import * as m1 from "./lib/brief-publico.functions.ts";
import * as m2 from "./lib/brief.functions.ts";
import * as m3 from "./lib/curadoria-ferramentas.functions.ts";
import * as m4 from "./lib/curadoria.functions.ts";
import * as m5 from "./lib/definicoes.functions.ts";
import * as m6 from "./lib/descricoes.functions.ts";
import * as m7 from "./lib/destinos.functions.ts";
import * as m8 from "./lib/emails-recebidos.functions.ts";
import * as m9 from "./lib/encurtar-descricao.functions.ts";
import * as m10 from "./lib/envio.functions.ts";
import * as m11 from "./lib/ferramentas.functions.ts";
import * as m12 from "./lib/fila-curadoria.functions.ts";
import * as m13 from "./lib/ia-leitura.functions.ts";
import * as m14 from "./lib/imagens.functions.ts";
import * as m15 from "./lib/newsletter-ia.functions.ts";
import * as m16 from "./lib/organizar-edicao.functions.ts";
import * as m17 from "./lib/pesquisar-fonte.functions.ts";
import * as m18 from "./lib/processar-noticias.functions.ts";
import * as m19 from "./lib/propor-apresentacao.functions.ts";
import * as m20 from "./lib/propor-pecas.functions.ts";
import * as m21 from "./lib/recomecar-edicao.functions.ts";
import * as m22 from "./lib/revista-preview.functions.ts";
import * as m23 from "./lib/revista-web.functions.ts";
import * as m24 from "./lib/subscricao.functions.ts";
import * as m25 from "./lib/verificar-links.functions.ts";
export const MODULES: Record<string, Record<string, unknown>> = {
  "brief-analytics": m0,
  "brief-publico": m1,
  "brief": m2,
  "curadoria-ferramentas": m3,
  "curadoria": m4,
  "definicoes": m5,
  "descricoes": m6,
  "destinos": m7,
  "emails-recebidos": m8,
  "encurtar-descricao": m9,
  "envio": m10,
  "ferramentas": m11,
  "fila-curadoria": m12,
  "ia-leitura": m13,
  "imagens": m14,
  "newsletter-ia": m15,
  "organizar-edicao": m16,
  "pesquisar-fonte": m17,
  "processar-noticias": m18,
  "propor-apresentacao": m19,
  "propor-pecas": m20,
  "recomecar-edicao": m21,
  "revista-preview": m22,
  "revista-web": m23,
  "subscricao": m24,
  "verificar-links": m25,
};
