// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
export type PapelIa = "extraccao" | "redaccao" | "verificacao";
export interface ModelosBrief {
    extraccao: string;
    redaccao: string;
    verificacao: string;
}
export declare function modelosBrief(sb: SupabaseClient): Promise<ModelosBrief>;
export interface PedidoIa {
    papel: PapelIa;
    operacao: string;
    system: string;
    user: string;
    briefId?: string | null;
    sb: SupabaseClient;
}
export interface RespostaIa<T> {
    dados: T | null;
    bruto: string;
    modelo: string;
    duracaoMs: number;
}
/**
 * Faz a chamada, devolve o JSON já interpretado e regista sempre o uso —
 * com sucesso ou com erro. O registo de custo nunca faz falhar a geração.
 */
export declare function chamarIaBrief<T>(pedido: PedidoIa): Promise<RespostaIa<T>>;
