// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { Brief, EstadoBrief, TipoBrief } from "./tipos.ts";
export type MotivoAtencao = "geracao_falhou" | "fonte_invalida" | "factualidade" | "proximidade";
export interface AtencaoBrief {
    motivos: MotivoAtencao[];
    precisa: boolean;
}
export declare function rotuloMotivoAtencao(m: MotivoAtencao): string;
type Parcial = Pick<Brief, "estado" | "erro" | "verificacao">;
/** Só é chamada a atenção quando há um problema concreto a resolver. */
export declare function avaliarAtencao(b: Parcial): AtencaoBrief;
/** Rótulo curto mostrado junto à notícia em «A Atualidade». */
export declare function rotuloEstadoCurto(tipo: TipoBrief, estado: EstadoBrief, aprovada: boolean): string;
export {};
