// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { Brief, EstadoBrief, TipoBrief } from "./tipos.ts";
export declare function transicaoPermitida(de: EstadoBrief, para: EstadoBrief): boolean;
export declare function garantirTransicao(de: EstadoBrief, para: EstadoBrief): void;
/**
 * Um Destaque só é publicável com a leitura aprovada; o Radar não exige
 * aprovação de opinião.
 */
export declare function exigeAprovacaoDeLeitura(tipo: TipoBrief): boolean;
/** Conteúdo mínimo para o Brief poder seguir para publicação. */
export declare function prontoParaPublicar(b: Pick<Brief, "tipo" | "estado" | "em_30_segundos" | "porque_interessa" | "leitura_aprovada" | "fonte_url">): {
    ok: boolean;
    motivos: string[];
};
