// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
export interface ResultadoFontePrimaria {
    url: string | null;
    publisher: string | null;
    reportagemPropria: boolean;
    adicionais: Array<{
        titulo: string;
        url: string;
    }>;
    motivo?: string;
}
export declare function identificarFontePrimaria(args: {
    sb: SupabaseClient;
    briefId?: string | null;
    titulo: string;
    factos: string[];
    urlFonte: string | null;
    htmlLigacoes?: string;
}): Promise<ResultadoFontePrimaria>;
