// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import { type SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import { type Brief, type BriefDaEdicao, type EstadoBrief, type ImplicacaoBrief, type LimitesBrief, type ParagrafoBrief, type TipoBrief } from "./tipos.ts";
/** Cliente privilegiado partilhado pelos módulos do motor do Brief. */
export declare function clienteBrief(sb?: SupabaseClient): SupabaseClient;
export interface ConteudoBrief {
    em_30_segundos: ParagrafoBrief[];
    porque_interessa: ImplicacaoBrief[];
    leitura_aprovada: string;
    fonte_url: string | null;
    fonte_primaria_url: string | null;
}
/** Impressão do conteúdo publicável — base do «alterado depois de publicado». */
export declare function hashConteudo(b: ConteudoBrief): string;
export declare function alteradoAposPublicacao(b: Brief): boolean;
export declare function limitesBrief(sb?: SupabaseClient): Promise<LimitesBrief>;
/** Interruptor de recuo: com os Briefs desligados nada é apresentado ao leitor. */
export declare function briefsActivos(sb?: SupabaseClient): Promise<boolean>;
export interface PedidoBrief {
    noticiaId: string;
    titulo: string;
    url?: string | null;
    tipo: TipoBrief;
    publisher?: string | null;
}
export interface ResultadoObterOuCriar {
    brief: Brief;
    criado: boolean;
}
/**
 * Segue a cadeia de repetições até à notícia canónica. Uma notícia marcada
 * como repetição de outra nunca origina um Brief próprio: a identidade é
 * sempre a da notícia original.
 */
export declare function resolverNoticiaCanonica(noticiaId: string, sb?: SupabaseClient): Promise<{
    id: string;
    titulo: string | null;
    url: string | null;
}>;
/**
 * Devolve o Brief da fonte pedida, criando-o só na primeira vez. Chamar duas
 * vezes com a mesma fonte devolve sempre a mesma linha e o mesmo endereço.
 * A identidade é sempre a da notícia canónica.
 */
export declare function obterOuCriarBrief(pedido: PedidoBrief, sb?: SupabaseClient): Promise<ResultadoObterOuCriar>;
export declare function associarBriefAEdicao(args: {
    briefId: string;
    edicaoId: string;
    papel: TipoBrief;
    ordem?: number;
    tituloApresentado?: string | null;
}, sb?: SupabaseClient): Promise<void>;
export declare function desassociarBriefDaEdicao(args: {
    briefId: string;
    edicaoId: string;
}, sb?: SupabaseClient): Promise<void>;
/**
 * Põe o Brief da notícia de acordo com o papel escolhido no editor:
 * cria ou reutiliza e associa quando há papel, desassocia quando a notícia
 * sai do email. Idempotente: repetir a chamada não muda nada.
 */
export declare function sincronizarPapelBrief(args: {
    edicaoId: string;
    noticiaId: string;
    papel: TipoBrief | null;
}, sb?: SupabaseClient): Promise<{
    briefId: string | null;
    criado: boolean;
}>;
export declare function listarBriefsDaEdicao(edicaoId: string, sb?: SupabaseClient): Promise<BriefDaEdicao[]>;
export declare function obterBriefPorSlug(slug: string, sb?: SupabaseClient): Promise<Brief | null>;
export interface AlteracaoConteudo {
    em_30_segundos?: ParagrafoBrief[];
    porque_interessa?: ImplicacaoBrief[];
    leitura_sugerida?: string;
    leitura_aprovada?: string;
    fonte_url?: string | null;
    fonte_publisher?: string | null;
    fonte_data?: string | null;
    fonte_primaria_url?: string | null;
}
/**
 * Grava conteúdo editorial. Mexer no texto aprovado revoga sempre a
 * aprovação: nada volta a ser apresentado como opinião do autor sem uma nova
 * decisão humana.
 */
export declare function actualizarConteudo(id: string, alteracao: AlteracaoConteudo, sb?: SupabaseClient): Promise<Brief>;
export declare function aprovarLeitura(args: {
    id: string;
    texto: string;
    quem: string;
}, sb?: SupabaseClient): Promise<Brief>;
export declare function revogarAprovacao(id: string, sb?: SupabaseClient): Promise<Brief>;
export declare function transitarEstado(args: {
    id: string;
    para: EstadoBrief;
    erro?: string | null;
}, sb?: SupabaseClient): Promise<Brief>;
export declare function registarVersao(args: {
    id: string;
    motivo: string;
    quem: string;
}, sb?: SupabaseClient): Promise<number>;
/** Endereço derivado do título, para pré-visualizar antes de criar. */
export declare function prevermSlug(titulo: string): string;
/**
 * Autosave da leitura em revisão. O texto trabalhado vive em
 * `leitura_sugerida`: só a aprovação o copia para `leitura_aprovada`. Mexer
 * numa leitura já aprovada revoga sempre a aprovação.
 */
export declare function guardarLeituraSugerida(args: {
    id: string;
    texto: string;
}, sb?: SupabaseClient): Promise<{
    estado: EstadoBrief;
    aprovada: boolean;
    revogou: boolean;
}>;
/**
 * Identidade editorial pública do Brief. O título é estável depois da
 * primeira publicação, mas continua deliberadamente editável — o endereço é
 * que nunca muda.
 */
export declare function guardarIdentidadeEditorial(args: {
    id: string;
    tituloEditorial?: string;
    teseEditorial?: string;
}, sb?: SupabaseClient): Promise<Brief>;
