// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import { type Intencao } from "./redaccao.server.ts";
import type { Brief } from "./tipos.ts";
export type ComponenteBrief = "tudo" | "em_30_segundos" | "porque_interessa" | "leitura_sugerida";
export interface PedidoGeracao {
    briefId: string;
    componente?: ComponenteBrief;
    intencao?: Intencao;
    sb?: SupabaseClient;
}
export interface ResultadoGeracao {
    brief: Brief;
    bloqueado: boolean;
    motivos: string[];
}
/**
 * Gera (ou regenera) o Brief. Duas chamadas seguidas nunca criam um segundo
 * Brief: trabalha-se sempre sobre a mesma linha, e o estado `a_gerar` serve
 * de tranca contra execuções sobrepostas.
 */
export declare function gerarBrief(pedido: PedidoGeracao): Promise<ResultadoGeracao>;
/**
 * Reformula quando a proximidade bloqueou: pede outro ângulo e volta a medir.
 */
export declare function reformularBrief(briefId: string, sb?: SupabaseClient): Promise<ResultadoGeracao>;
/** Nova passagem de verificação, sem reescrever nada. */
export declare function reverificarBrief(briefId: string, sb?: SupabaseClient): Promise<ResultadoGeracao>;
