// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
export type DecisaoProximidade = "ok" | "rever" | "bloqueado";
export interface ResultadoProximidade {
    /** 0 a 1. Quanto maior, mais perto o nosso texto está da fonte. */
    score: number;
    decisao: DecisaoProximidade;
    /** Sequências mínimas que justificam a decisão (no máximo 5). */
    trechos: string[];
    /** Maior número de palavras seguidas iguais encontrado. */
    maiorSequencia: number;
}
export declare const LIMIAR_REVER = 0.12;
export declare const LIMIAR_BLOQUEIO = 0.24;
/** Uma sequência igual desta dimensão é, por si só, cópia. */
export declare const PALAVRAS_SEQUENCIA_BLOQUEIO = 14;
export declare function normalizar(texto: string): string;
/** Conjunto de sequências de `n` palavras. */
export declare function shingles(texto: string, n?: number): Set<string>;
/**
 * Compara o nosso texto com o texto da fonte. O texto da fonte é transitório:
 * nada dele é devolvido além dos trechos mínimos que justificam a decisão.
 */
export declare function avaliarProximidade(nosso: string, fonte: string): ResultadoProximidade;
