// GENERATED by scripts/port-newsletter.py from the server tree — do not edit.
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.57.4";
import type { BriefDaEdicao, TipoBrief } from "./tipos.ts";
/** Bloco congelado no snapshot, por peça. */
export interface LigacaoBrief {
    briefId: string;
    versao: number;
    tipo: TipoBrief;
    /** Papel na edição. Hoje igual ao tipo; fica explícito para o histórico. */
    papel: TipoBrief;
    ordem: number;
    slug: string;
    url: string;
    /** Identidade editorial do Brief — o que a página pública mostra. */
    tituloEditorial: string;
    /** Título usado nesta edição, que pode ser diferente do editorial. */
    tituloApresentado: string;
    fonteUrl: string;
}
export declare function caminhoBrief(slug: string): string;
export interface ProblemaBrief {
    noticiaId: string | null;
    titulo: string;
    motivo: string;
}
export interface ValidacaoBriefs {
    /** Peças com Brief pronto a publicar, por notícia. */
    prontos: BriefDaEdicao[];
    /** Destaques sem leitura aprovada. */
    leiturasPorAprovar: ProblemaBrief[];
    /** Fonte em falta, inválida ou indisponível. */
    fontes: ProblemaBrief[];
    /** Factualidade ou proximidade bloqueadas, geração falhada. */
    verificacoes: ProblemaBrief[];
    /** Conteúdo em falta (Brief por gerar, sem texto). */
    incompletos: ProblemaBrief[];
    totalDestaques: number;
    totalRadar: number;
    /** Peças associadas à edição (Destaques + Radar). */
    total: number;
    /** Peças sem afirmação por sustentar, proximidade bloqueada ou geração falhada. */
    factualidadeOk: number;
    /** Peças com fonte original válida. */
    fontesOk: number;
}
export declare function validarBriefsDaEdicao(edicaoId: string, sb?: SupabaseClient): Promise<ValidacaoBriefs>;
export interface ResultadoPublicacaoBriefs {
    publicados: number;
    reutilizados: number;
    ligacoes: Record<string, LigacaoBrief>;
    /** Peças cuja versão não pôde ser congelada — bloqueio real do envio. */
    naoCongelaveis: ProblemaBrief[];
}
/**
 * Publica os Briefs prontos desta edição e devolve as ligações por notícia.
 * Idempotente: um Brief já publicado e sem alterações não é tocado.
 */
export declare function publicarBriefsDaEdicao(edicaoId: string, sb?: SupabaseClient): Promise<ResultadoPublicacaoBriefs>;
/**
 * Ligações já publicadas desta edição, sem publicar nada.
 * Usada na composição e na pré-visualização.
 */
export declare function ligacoesBriefsDaEdicao(edicaoId: string, sb?: SupabaseClient): Promise<Record<string, LigacaoBrief>>;
export interface ConfirmacaoUrls {
    ok: boolean;
    falhados: Array<{
        slug: string;
        url: string;
        status: number;
    }>;
}
/**
 * Bate à porta de cada página antes de o endereço entrar no email.
 * Uma página de Brief interna que não responde é bloqueio real.
 */
export declare function confirmarUrlsPublicas(ligacoes: Record<string, LigacaoBrief>): Promise<ConfirmacaoUrls>;
